import { LessonLayout } from '../../components/layout';
import { Definition, Theorem, Example, Math } from '../../components/common';
import 'katex/dist/katex.min.css';

export default function Section29() {
  return (
    <LessonLayout sectionId={29}>
      <div className="space-y-8">
        {/* Introduction */}
        <section>
          <p className="text-lg text-dark-300 leading-relaxed">
            <strong>Algebraic coding theory</strong> uses polynomial rings and finite fields to construct
            error-correcting codes. These codes are essential for reliable digital communication and storage.
          </p>
        </section>

        {/* Basic Concepts */}
        <section>
          <h3 className="text-xl font-semibold mb-4">Error-Correcting Codes</h3>

          <Definition title="Linear Code">
            <p>
              A <strong>linear code</strong> <Math>C</Math> of length <Math>n</Math> over a field <Math>F</Math>
              is a vector subspace of <Math>{'F^n'}</Math>.
            </p>
            <p className="mt-2">
              If <Math>{'\\dim(C) = k'}</Math>, we call <Math>C</Math> an <strong>[n, k] code</strong>.
            </p>
          </Definition>

          <Definition title="Hamming Distance">
            <p>
              The <strong>Hamming distance</strong> <Math>{'d(u, v)'}</Math> between codewords <Math>u</Math>
              and <Math>v</Math> is the number of positions where they differ.
            </p>
            <p className="mt-2">
              The <strong>minimum distance</strong> <Math>d</Math> of a code is the smallest distance
              between distinct codewords.
            </p>
          </Definition>

          <div className="card">
            <h4 className="font-semibold mb-3">Error Detection and Correction</h4>
            <ul className="space-y-2 text-dark-300">
              <li>A code with minimum distance <Math>d</Math> can detect <Math>{'d-1'}</Math> errors</li>
              <li>A code with minimum distance <Math>d</Math> can correct <Math>{'\\lfloor(d-1)/2\\rfloor'}</Math> errors</li>
            </ul>
          </div>
        </section>

        {/* Cyclic Codes */}
        <section>
          <h3 className="text-xl font-semibold mb-4">Cyclic Codes</h3>

          <Definition title="Cyclic Code">
            <p>
              A linear code <Math>C</Math> is <strong>cyclic</strong> if whenever <Math>{'(c_0, c_1, ..., c_{n-1}) \\in C'}</Math>,
              then <Math>{'(c_{n-1}, c_0, ..., c_{n-2}) \\in C'}</Math> (cyclic shift).
            </p>
          </Definition>

          <Theorem title="Polynomial Representation">
            <p>
              A cyclic code of length <Math>n</Math> over <Math>F</Math> corresponds to an ideal in
              <Math>{'F[x]/(x^n - 1)'}</Math>. The code is generated by a polynomial <Math>{'g(x)'}</Math>
              dividing <Math>{'x^n - 1'}</Math>.
            </p>
          </Theorem>

          <Example title="Polynomial Encoding">
            <div className="bg-dark-900 p-4 rounded">
              <p>Message: <Math>{'m(x) = 1 + x^2'}</Math></p>
              <p>Generator: <Math>{'g(x) = 1 + x + x^3'}</Math></p>
              <p className="mt-2">Codeword: <Math>{'c(x) = m(x) \\cdot g(x)'}</Math></p>
              <p><Math>{'= (1 + x^2)(1 + x + x^3)'}</Math></p>
              <p className="text-primary-400"><Math>{'= 1 + x + x^2 + x^3 + x^4 + x^5'}</Math></p>
            </div>
          </Example>
        </section>

        {/* BCH Codes */}
        <section>
          <h3 className="text-xl font-semibold mb-4">BCH Codes</h3>

          <Definition title="BCH Code">
            <p>
              <strong>BCH codes</strong> (Bose-Chaudhuri-Hocquenghem) are cyclic codes with guaranteed
              minimum distance. They use roots of unity in extension fields.
            </p>
          </Definition>

          <div className="card">
            <h4 className="font-semibold mb-3">Construction</h4>
            <p className="text-dark-300">
              Let <Math>{'\\alpha'}</Math> be a primitive <Math>n</Math>th root of unity in an extension
              of <Math>{'\\mathbb{Z}_p'}</Math>. The BCH code with designed distance <Math>d</Math> has
              generator polynomial with roots <Math>{'\\alpha, \\alpha^2, ..., \\alpha^{d-1}'}</Math>.
            </p>
          </div>
        </section>

        {/* Reed-Solomon Codes */}
        <section>
          <h3 className="text-xl font-semibold mb-4">Reed-Solomon Codes</h3>

          <Definition title="Reed-Solomon Code">
            <p>
              A <strong>Reed-Solomon code</strong> is a BCH code where the codeword symbols come from
              a finite field <Math>{'F_q'}</Math> and the code length is <Math>{'n = q - 1'}</Math>.
            </p>
          </Definition>

          <div className="card">
            <h4 className="font-semibold mb-3">Properties</h4>
            <ul className="space-y-2 text-dark-300">
              <li>Parameters: <Math>{'[n, k, n-k+1]'}</Math></li>
              <li>Achieves the Singleton bound (MDS codes)</li>
              <li>Can correct up to <Math>{'(n-k)/2'}</Math> symbol errors</li>
              <li>Efficient decoding algorithms exist</li>
            </ul>
          </div>

          <Example title="RS Applications">
            <div className="space-y-2">
              <div className="bg-dark-900 p-3 rounded">
                <p className="font-semibold text-primary-400">CDs and DVDs</p>
                <p className="text-dark-300 text-sm">Cross-interleaved RS codes handle scratches</p>
              </div>
              <div className="bg-dark-900 p-3 rounded">
                <p className="font-semibold text-primary-400">QR Codes</p>
                <p className="text-dark-300 text-sm">RS codes for error correction levels L/M/Q/H</p>
              </div>
              <div className="bg-dark-900 p-3 rounded">
                <p className="font-semibold text-primary-400">Deep Space Communication</p>
                <p className="text-dark-300 text-sm">Voyager probes, Mars rovers</p>
              </div>
            </div>
          </Example>
        </section>

        {/* Decoding */}
        <section>
          <h3 className="text-xl font-semibold mb-4">Decoding</h3>

          <div className="card">
            <h4 className="font-semibold mb-3">Syndrome Decoding</h4>
            <p className="text-dark-300 mb-3">
              Received word <Math>{'r(x) = c(x) + e(x)'}</Math> where <Math>{'e(x)'}</Math> is the error.
            </p>
            <ol className="list-decimal list-inside space-y-1 text-dark-300">
              <li>Compute syndromes <Math>{'S_i = r(\\alpha^i)'}</Math></li>
              <li>Find error locator polynomial from syndromes</li>
              <li>Find error positions (roots of locator)</li>
              <li>Compute error values and correct</li>
            </ol>
          </div>
        </section>

        {/* Summary */}
        <section className="card">
          <h3 className="text-xl font-semibold mb-4">Key Takeaways</h3>
          <ul className="space-y-2 text-dark-300">
            <li>
              <strong>Cyclic codes</strong> correspond to ideals in <Math>{'F[x]/(x^n-1)'}</Math>.
            </li>
            <li>
              <strong>BCH codes</strong> have guaranteed minimum distance via root structure.
            </li>
            <li>
              <strong>Reed-Solomon codes</strong> are optimal for burst error correction.
            </li>
            <li>
              Finite field arithmetic is essential for encoding and decoding.
            </li>
            <li>
              These codes are used everywhere: CDs, QR codes, satellites, hard drives.
            </li>
          </ul>
        </section>
      </div>
    </LessonLayout>
  );
}
