import { LessonLayout } from '../../components/layout';
import { Definition, Theorem, Example, Math, MathBlock } from '../../components/common';
import { GeneratorsQuiz } from '../../components/visualizations';
import 'katex/dist/katex.min.css';

export default function Section07() {
  return (
    <LessonLayout sectionId={7}>
      <div className="space-y-8">
        {/* Introduction */}
        <section>
          <p className="text-lg text-dark-300 leading-relaxed">
            We've seen that cyclic groups are generated by a single element. More generally, any group
            can be described by a <strong>generating set</strong>—a subset whose elements combine to
            produce every element of the group. <strong>Cayley digraphs</strong> visualize this structure.
          </p>
        </section>

        {/* Generating Sets */}
        <Definition title="Generating Set">
          <p>
            A subset <Math>S</Math> of a group <Math>G</Math> is a <strong>generating set</strong> if
            every element of <Math>G</Math> can be expressed as a finite product of elements from
            <Math>S</Math> and their inverses.
          </p>
          <MathBlock>{'G = \\langle S \\rangle'}</MathBlock>
          <p className="mt-2">
            We say <Math>S</Math> <strong>generates</strong> <Math>G</Math>, or <Math>G</Math> is
            <strong> generated by</strong> <Math>S</Math>.
          </p>
        </Definition>

        <Example title="Generating Sets">
          <div className="space-y-3">
            <div className="bg-dark-900 p-3 rounded">
              <p className="font-semibold text-primary-400"><Math>{'\\mathbb{Z}'}</Math></p>
              <p className="text-dark-300">Generated by <Math>{'{1}'}</Math> or <Math>{'{-1}'}</Math> or <Math>{'{2, 3}'}</Math></p>
            </div>
            <div className="bg-dark-900 p-3 rounded">
              <p className="font-semibold text-primary-400"><Math>{'\\mathbb{Z}_6'}</Math></p>
              <p className="text-dark-300">Generated by <Math>{'{1}'}</Math> or <Math>{'{5}'}</Math> (generators) or <Math>{'{2, 3}'}</Math></p>
            </div>
            <div className="bg-dark-900 p-3 rounded">
              <p className="font-semibold text-primary-400"><Math>{'D_3'}</Math></p>
              <p className="text-dark-300">Generated by <Math>{'{r, s}'}</Math> where <Math>r</Math> is rotation, <Math>s</Math> is reflection</p>
            </div>
            <div className="bg-dark-900 p-3 rounded">
              <p className="font-semibold text-primary-400"><Math>{'S_n'}</Math></p>
              <p className="text-dark-300">Generated by all transpositions, or by <Math>{'{(1\\,2), (1\\,2\\,...\\,n)}'}</Math></p>
            </div>
          </div>
        </Example>

        <div className="callout-info">
          <p>
            <strong>Minimal generating sets:</strong> A generating set is <em>minimal</em> if removing
            any element means it no longer generates the group. The minimum size of a generating set
            is called the <strong>rank</strong> of the group.
          </p>
        </div>

        {/* Cayley Digraphs */}
        <section>
          <h3 className="text-xl font-semibold mb-4">Cayley Digraphs</h3>

          <Definition title="Cayley Digraph">
            <p>
              Given a group <Math>G</Math> and a generating set <Math>S</Math>, the
              <strong> Cayley digraph</strong> <Math>{'\\text{Cay}(G, S)'}</Math> is a directed graph where:
            </p>
            <ul className="list-disc list-inside mt-2 space-y-1">
              <li><strong>Vertices:</strong> Elements of <Math>G</Math></li>
              <li><strong>Edges:</strong> For each <Math>{'g \\in G'}</Math> and <Math>{'s \\in S'}</Math>,
                draw an edge from <Math>g</Math> to <Math>gs</Math> (colored/labeled by <Math>s</Math>)</li>
            </ul>
          </Definition>

          <div className="card">
            <h4 className="font-semibold mb-3">Properties of Cayley Digraphs</h4>
            <ul className="space-y-2 text-dark-300">
              <li>
                Every vertex has exactly <Math>|S|</Math> outgoing edges (one for each generator)
              </li>
              <li>
                The graph is connected (since <Math>S</Math> generates <Math>G</Math>)
              </li>
              <li>
                The graph is vertex-transitive (looks the same from any vertex)
              </li>
              <li>
                If <Math>{'s \\in S'}</Math> has order 2, the edge for <Math>s</Math> can be undirected
              </li>
            </ul>
          </div>
        </section>

        {/* Example Cayley Digraphs */}
        <section>
          <h3 className="text-xl font-semibold mb-4">Example Cayley Digraphs</h3>

          <Example title="Z₄ with generator {1}">
            <div className="bg-dark-950 p-6 rounded-lg">
              <svg viewBox="0 0 200 200" className="w-48 h-48 mx-auto">
                {/* Vertices */}
                <circle cx="100" cy="30" r="20" fill="#1e293b" stroke="#6366f1" strokeWidth="2" />
                <text x="100" y="35" textAnchor="middle" fill="white" fontSize="14">0</text>

                <circle cx="170" cy="100" r="20" fill="#1e293b" stroke="#6366f1" strokeWidth="2" />
                <text x="170" y="105" textAnchor="middle" fill="white" fontSize="14">1</text>

                <circle cx="100" cy="170" r="20" fill="#1e293b" stroke="#6366f1" strokeWidth="2" />
                <text x="100" y="175" textAnchor="middle" fill="white" fontSize="14">2</text>

                <circle cx="30" cy="100" r="20" fill="#1e293b" stroke="#6366f1" strokeWidth="2" />
                <text x="30" y="105" textAnchor="middle" fill="white" fontSize="14">3</text>

                {/* Edges */}
                <path d="M 115 42 L 155 88" stroke="#f59e0b" strokeWidth="2" markerEnd="url(#arrow)" />
                <path d="M 158 115 L 115 158" stroke="#f59e0b" strokeWidth="2" markerEnd="url(#arrow)" />
                <path d="M 85 158 L 42 115" stroke="#f59e0b" strokeWidth="2" markerEnd="url(#arrow)" />
                <path d="M 42 85 L 85 42" stroke="#f59e0b" strokeWidth="2" markerEnd="url(#arrow)" />

                <defs>
                  <marker id="arrow" markerWidth="10" markerHeight="7" refX="9" refY="3.5" orient="auto">
                    <polygon points="0 0, 10 3.5, 0 7" fill="#f59e0b" />
                  </marker>
                </defs>
              </svg>
              <p className="text-center text-dark-400 mt-2">A cycle of length 4</p>
            </div>
          </Example>

          <Example title="Z₆ with generators {2, 3}">
            <div className="bg-dark-900 p-4 rounded">
              <p className="text-dark-300 mb-2">
                With two generators, we get a more complex graph:
              </p>
              <ul className="list-disc list-inside space-y-1 text-dark-400 text-sm">
                <li>Edges for +2: 0→2→4→0 and 1→3→5→1 (two triangles)</li>
                <li>Edges for +3: 0→3→0, 1→4→1, 2→5→2 (three pairs)</li>
              </ul>
            </div>
          </Example>

          <Example title="D₃ with generators {r, s}">
            <p className="text-dark-300 mb-3">
              The Cayley digraph of <Math>D_3</Math> with <Math>r</Math> (rotation by 120°) and
              <Math>s</Math> (reflection):
            </p>
            <ul className="list-disc list-inside space-y-2 text-dark-400">
              <li>6 vertices: <Math>{'e, r, r^2, s, sr, sr^2'}</Math></li>
              <li>Red edges for <Math>r</Math>: form two triangles</li>
              <li>Blue edges for <Math>s</Math>: connect corresponding elements (undirected since <Math>{'s^2 = e'}</Math>)</li>
            </ul>
          </Example>
        </section>

        {/* Using Cayley Digraphs */}
        <section>
          <h3 className="text-xl font-semibold mb-4">Reading Cayley Digraphs</h3>

          <div className="card">
            <h4 className="font-semibold mb-3">Information from the Graph</h4>
            <ul className="space-y-3 text-dark-300">
              <li>
                <strong>Order of group:</strong> Number of vertices
              </li>
              <li>
                <strong>Order of generator <Math>s</Math>:</strong> Length of the cycle using only <Math>s</Math>-edges
              </li>
              <li>
                <strong>Abelian check:</strong> If <Math>G</Math> is abelian, following edges in different orders
                leads to the same vertex
              </li>
              <li>
                <strong>Subgroups:</strong> Subgraphs using only some generators
              </li>
            </ul>
          </div>

          <Theorem title="Cayley's Theorem Revisited">
            <p>
              Every group <Math>G</Math> is isomorphic to a subgroup of some symmetric group.
              The Cayley digraph provides an explicit way to see this embedding.
            </p>
          </Theorem>
        </section>

        {/* Word Metric */}
        <section>
          <h3 className="text-xl font-semibold mb-4">Word Length and Distance</h3>

          <Definition title="Word Length">
            <p>
              Given a generating set <Math>S</Math>, the <strong>word length</strong> of an element
              <Math>{'g \\in G'}</Math> is the minimum number of generators (and their inverses)
              needed to express <Math>g</Math>.
            </p>
          </Definition>

          <div className="card">
            <p className="text-dark-300 mb-3">
              In the Cayley digraph, the word length of <Math>g</Math> equals the shortest path
              from the identity <Math>e</Math> to <Math>g</Math>.
            </p>
            <p className="text-dark-300">
              This defines the <strong>word metric</strong>: <Math>{'d(g, h)'}</Math> = word length of <Math>{'g^{-1}h'}</Math>.
            </p>
          </div>

          <Example title="Word Length in Z₆">
            <p className="mb-2">With generator <Math>{'{1}'}</Math>:</p>
            <div className="grid grid-cols-6 gap-2 font-mono text-sm">
              {[0, 1, 2, 3, 4, 5].map(n => (
                <div key={n} className="bg-dark-900 p-2 rounded text-center">
                  <div className="text-dark-400">{n}</div>
                  <div className="text-primary-400">len: {window.Math.min(n, 6-n)}</div>
                </div>
              ))}
            </div>
            <p className="text-dark-400 text-sm mt-2">
              (Using <Math>-1</Math> as inverse, so 5 = -1 has length 1)
            </p>
          </Example>
        </section>

        {/* Presentations */}
        <section>
          <h3 className="text-xl font-semibold mb-4">Group Presentations</h3>

          <Definition title="Group Presentation">
            <p>
              A <strong>presentation</strong> of a group specifies:
            </p>
            <ul className="list-disc list-inside mt-2 space-y-1">
              <li><strong>Generators:</strong> A set <Math>S</Math></li>
              <li><strong>Relations:</strong> Equations that the generators satisfy</li>
            </ul>
            <p className="mt-2">Notation: <Math>{'\\langle S \\mid R \\rangle'}</Math></p>
          </Definition>

          <Example title="Common Presentations">
            <div className="space-y-3">
              <div className="bg-dark-900 p-3 rounded">
                <p className="font-semibold text-primary-400"><Math>{'\\mathbb{Z}_n'}</Math></p>
                <p className="font-mono text-sm"><Math>{'\\langle a \\mid a^n = e \\rangle'}</Math></p>
              </div>
              <div className="bg-dark-900 p-3 rounded">
                <p className="font-semibold text-primary-400"><Math>{'\\mathbb{Z}'}</Math></p>
                <p className="font-mono text-sm"><Math>{'\\langle a \\mid \\, \\rangle'}</Math> (no relations)</p>
              </div>
              <div className="bg-dark-900 p-3 rounded">
                <p className="font-semibold text-primary-400"><Math>D_n</Math></p>
                <p className="font-mono text-sm"><Math>{'\\langle r, s \\mid r^n = s^2 = e, srs = r^{-1} \\rangle'}</Math></p>
              </div>
            </div>
          </Example>
        </section>

        {/* Practice Quiz */}
        <section>
          <h3 className="text-xl font-semibold mb-4">Practice: Generators & Presentations</h3>
          <p className="text-dark-300 mb-6">
            Test your understanding of generating sets, group presentations, and Cayley digraphs.
            Each quiz generates 10 random questions.
          </p>
          <GeneratorsQuiz />
        </section>

        {/* Summary */}
        <section className="card">
          <h3 className="text-xl font-semibold mb-4">Key Takeaways</h3>
          <ul className="space-y-2 text-dark-300">
            <li>
              A generating set <Math>S</Math> produces all group elements through products.
            </li>
            <li>
              Cayley digraphs visualize group structure with vertices for elements and
              colored edges for generators.
            </li>
            <li>
              Word length measures how many generators are needed to express an element.
            </li>
            <li>
              Group presentations describe groups via generators and relations.
            </li>
            <li>
              Cayley digraphs are always connected and vertex-transitive.
            </li>
          </ul>
        </section>
      </div>
    </LessonLayout>
  );
}
