import { LessonLayout } from '../../components/layout';
import { Definition, Theorem, Example, Math, MathBlock } from '../../components/common';
import { CyclicGroupWheel } from '../../components/visualizations';
import 'katex/dist/katex.min.css';

export default function Section06() {
  const totients: Record<number, number> = { 2: 1, 3: 2, 4: 2, 5: 4, 6: 2, 8: 4, 10: 4, 12: 4 };

  return (
    <LessonLayout sectionId={6}>
      <div className="space-y-8">
        {/* Introduction */}
        <section>
          <p className="text-lg text-dark-300 leading-relaxed">
            <strong>Cyclic groups</strong> are the simplest groups—they are generated by a single element.
            Despite their simplicity, they form the building blocks for understanding all finite abelian groups
            and play a crucial role throughout algebra and number theory.
          </p>
        </section>

        {/* Definition */}
        <Definition title="Cyclic Group">
          <p>
            A group <Math>G</Math> is <strong>cyclic</strong> if there exists an element{' '}
            <Math>{'g \\in G'}</Math> such that every element of <Math>G</Math> is a power of{' '}
            <Math>g</Math>:
          </p>
          <MathBlock>{'G = \\langle g \\rangle = \\{g^n : n \\in \\mathbb{Z}\\}'}</MathBlock>
          <p className="mt-2">
            The element <Math>g</Math> is called a <strong>generator</strong> of <Math>G</Math>.
          </p>
        </Definition>

        {/* Interactive Cyclic Group Wheel */}
        <section>
          <h3 className="text-xl font-semibold mb-4">Interactive: Cyclic Group Wheel</h3>
          <p className="text-dark-300 mb-4">
            Explore the structure of cyclic groups <Math>{'\\mathbb{Z}_n'}</Math>. Click on elements
            to see the subgroup they generate. Generators (elements of order <Math>n</Math>)
            are shown in amber.
          </p>
          <CyclicGroupWheel n={12} maxN={20} />
        </section>

        {/* Finite vs Infinite Cyclic Groups */}
        <div className="grid md:grid-cols-2 gap-4">
          <div className="card">
            <h4 className="font-semibold mb-3">Finite Cyclic Groups</h4>
            <p className="text-dark-300 mb-2">
              If <Math>{'G = \\langle g \\rangle'}</Math> has finite order <Math>n</Math>, then:
            </p>
            <MathBlock>{'G = \\{e, g, g^2, ..., g^{n-1}\\}'}</MathBlock>
            <p className="text-dark-300 mt-2">
              The canonical example is <Math>{'\\mathbb{Z}_n'}</Math>, integers mod <Math>n</Math>.
            </p>
          </div>
          <div className="card">
            <h4 className="font-semibold mb-3">Infinite Cyclic Groups</h4>
            <p className="text-dark-300 mb-2">
              If <Math>{'G = \\langle g \\rangle'}</Math> has infinite order, then:
            </p>
            <MathBlock>{'G = \\{..., g^{-2}, g^{-1}, e, g, g^2, ...\\}'}</MathBlock>
            <p className="text-dark-300 mt-2">
              The canonical example is <Math>{'\\mathbb{Z}'}</Math>, the integers under addition.
            </p>
          </div>
        </div>

        {/* Element Order */}
        <Definition title="Order of an Element">
          <p>
            The <strong>order</strong> of an element <Math>g</Math> in a group, denoted{' '}
            <Math>|g|</Math> or <Math>{'\\text{ord}(g)'}</Math>, is the smallest positive
            integer <Math>n</Math> such that <Math>{'g^n = e'}</Math>.
          </p>
          <p className="mt-2">
            If no such <Math>n</Math> exists, we say <Math>g</Math> has{' '}
            <strong>infinite order</strong>.
          </p>
        </Definition>

        <Theorem title="Order and Subgroup Size">
          <p>
            For any element <Math>g</Math> in a group:
          </p>
          <MathBlock>{'|\\langle g \\rangle| = |g|'}</MathBlock>
          <p className="mt-2">
            The order of the cyclic subgroup generated by <Math>g</Math> equals the order of{' '}
            <Math>g</Math>.
          </p>
        </Theorem>

        {/* Generators */}
        <section>
          <h3 className="text-xl font-semibold mb-4">Generators of <Math>{'\\mathbb{Z}_n'}</Math></h3>

          <Theorem title="Generators of Z_n">
            <p>
              An element <Math>{'k \\in \\mathbb{Z}_n'}</Math> is a generator if and only if{' '}
              <Math>{'\\gcd(k, n) = 1'}</Math>.
            </p>
            <p className="mt-2">
              The number of generators of <Math>{'\\mathbb{Z}_n'}</Math> is <Math>{'\\phi(n)'}</Math>,
              Euler's totient function.
            </p>
          </Theorem>

          <Example title="Generators of Z₁₂">
            <p className="mb-3">
              The integers from 1 to 11 that are coprime to 12 are: 1, 5, 7, 11.
            </p>
            <p className="mb-3">
              So <Math>{'\\mathbb{Z}_{12}'}</Math> has exactly <Math>{'\\phi(12) = 4'}</Math> generators.
            </p>
            <div className="bg-dark-900 p-4 rounded-lg font-mono text-sm space-y-1">
              <p><Math>{'\\langle 1 \\rangle'}</Math> = 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11</p>
              <p><Math>{'\\langle 5 \\rangle'}</Math> = 0, 5, 10, 3, 8, 1, 6, 11, 4, 9, 2, 7</p>
              <p><Math>{'\\langle 7 \\rangle'}</Math> = 0, 7, 2, 9, 4, 11, 6, 1, 8, 3, 10, 5</p>
              <p><Math>{'\\langle 11 \\rangle'}</Math> = 0, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1</p>
            </div>
          </Example>
        </section>

        {/* Order Formula */}
        <Theorem title="Order of Elements in Z_n">
          <p>
            In <Math>{'\\mathbb{Z}_n'}</Math>, the order of an element <Math>k</Math> is:
          </p>
          <MathBlock>{'|k| = \\frac{n}{\\gcd(k, n)}'}</MathBlock>
        </Theorem>

        <Example title="Orders in Z₁₂">
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-dark-700">
                  <th className="px-3 py-2 text-left">Element k</th>
                  <th className="px-3 py-2 text-left">gcd(k, 12)</th>
                  <th className="px-3 py-2 text-left">Order = 12/gcd</th>
                </tr>
              </thead>
              <tbody>
                {[0, 1, 2, 3, 4, 5, 6].map(k => {
                  const g = [12, 1, 2, 3, 4, 1, 6][k];
                  const ord = k === 0 ? 1 : 12 / g;
                  return (
                    <tr key={k} className="border-b border-dark-800">
                      <td className="px-3 py-2">{k}</td>
                      <td className="px-3 py-2">{g}</td>
                      <td className="px-3 py-2">{ord}</td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </Example>

        {/* Subgroups of Cyclic Groups */}
        <Theorem title="Subgroups of Cyclic Groups">
          <p>Every subgroup of a cyclic group is cyclic.</p>
        </Theorem>

        <Theorem title="Subgroups of Z_n">
          <p>
            For each divisor <Math>d</Math> of <Math>n</Math>, there is exactly one
            subgroup of <Math>{'\\mathbb{Z}_n'}</Math> of order <Math>d</Math>, namely:
          </p>
          <MathBlock>{'\\langle n/d \\rangle = \\{0, n/d, 2(n/d), ..., (d-1)(n/d)\\}'}</MathBlock>
        </Theorem>

        <div className="callout-info">
          <p>
            <strong>Counting Subgroups:</strong> The number of subgroups of <Math>{'\\mathbb{Z}_n'}</Math>{' '}
            equals the number of divisors of <Math>n</Math>.
          </p>
          <p className="mt-2">
            For example, <Math>{'\\mathbb{Z}_{12}'}</Math> has divisors {'{1, 2, 3, 4, 6, 12}'}, so it has
            exactly 6 subgroups.
          </p>
        </div>

        {/* Classification Theorem */}
        <Theorem title="Classification of Cyclic Groups">
          <p>
            Every cyclic group is isomorphic to either <Math>{'\\mathbb{Z}'}</Math> (if infinite) or{' '}
            <Math>{'\\mathbb{Z}_n'}</Math> for some <Math>{'n \\geq 1'}</Math> (if finite).
          </p>
          <p className="mt-2">
            Moreover, <Math>{'\\mathbb{Z}_m \\cong \\mathbb{Z}_n'}</Math> if and only if{' '}
            <Math>m = n</Math>.
          </p>
        </Theorem>

        {/* Important Properties */}
        <section className="card">
          <h3 className="text-xl font-semibold mb-4">Key Properties of Cyclic Groups</h3>
          <ul className="space-y-3 text-dark-300">
            <li>
              <strong>Abelian:</strong> Every cyclic group is abelian (commutative).
            </li>
            <li>
              <strong>Simple structure:</strong> Completely determined by its order.
            </li>
            <li>
              <strong>Subgroups:</strong> All subgroups are cyclic and in bijection with divisors of{' '}
              <Math>n</Math>.
            </li>
            <li>
              <strong>Generators:</strong> Exactly <Math>{'\\phi(n)'}</Math> generators for{' '}
              <Math>{'\\mathbb{Z}_n'}</Math>.
            </li>
            <li>
              <strong>Direct products:</strong>{' '}
              <Math>{'\\mathbb{Z}_m \\times \\mathbb{Z}_n \\cong \\mathbb{Z}_{mn}'}</Math> iff{' '}
              <Math>{'\\gcd(m, n) = 1'}</Math>.
            </li>
          </ul>
        </section>

        {/* Euler's Totient */}
        <Definition title="Euler's Totient Function">
          <p>
            <Math>{'\\phi(n)'}</Math> counts the positive integers up to <Math>n</Math>{' '}
            that are relatively prime to <Math>n</Math>.
          </p>
          <p className="mt-2">For prime powers:</p>
          <MathBlock>{'\\phi(p^k) = p^k - p^{k-1} = p^{k-1}(p-1)'}</MathBlock>
          <p>For general <Math>n</Math>:</p>
          <MathBlock>{'\\phi(n) = n \\prod_{p | n} \\left(1 - \\frac{1}{p}\\right)'}</MathBlock>
        </Definition>

        <Example title="Computing φ(n)">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {[2, 3, 4, 5, 6, 8, 10, 12].map(n => (
              <div key={n} className="bg-dark-900 p-3 rounded-lg text-center">
                <div className="text-sm text-dark-400">n = {n}</div>
                <div className="text-xl font-mono text-primary-400">φ({n}) = {totients[n]}</div>
              </div>
            ))}
          </div>
        </Example>

        {/* Applications */}
        <section className="card">
          <h3 className="text-xl font-semibold mb-4">Applications</h3>
          <div className="space-y-4 text-dark-300">
            <div>
              <h4 className="font-semibold text-dark-200">Cryptography (RSA)</h4>
              <p>
                The security of RSA depends on properties of cyclic groups{' '}
                <Math>{'\\mathbb{Z}_n^*'}</Math> and Euler's theorem.
              </p>
            </div>
            <div>
              <h4 className="font-semibold text-dark-200">Roots of Unity</h4>
              <p>
                The <Math>n</Math>th roots of unity form a cyclic group of order{' '}
                <Math>n</Math> under multiplication in <Math>{'\\mathbb{C}'}</Math>.
              </p>
            </div>
            <div>
              <h4 className="font-semibold text-dark-200">Modular Arithmetic</h4>
              <p>
                Understanding cyclic groups is essential for working with modular arithmetic
                in computer science and number theory.
              </p>
            </div>
          </div>
        </section>

        {/* Summary */}
        <section className="card">
          <h3 className="text-xl font-semibold mb-4">Key Takeaways</h3>
          <ul className="space-y-2 text-dark-300">
            <li>
              A cyclic group is generated by a single element.
            </li>
            <li>
              <Math>{'\\mathbb{Z}_n'}</Math> has <Math>{'\\phi(n)'}</Math> generators.
            </li>
            <li>
              The order of <Math>k</Math> in <Math>{'\\mathbb{Z}_n'}</Math> is{' '}
              <Math>{'n/\\gcd(k,n)'}</Math>.
            </li>
            <li>
              Every subgroup of a cyclic group is cyclic.
            </li>
            <li>
              Subgroups of <Math>{'\\mathbb{Z}_n'}</Math> correspond to divisors of <Math>n</Math>.
            </li>
          </ul>
        </section>
      </div>
    </LessonLayout>
  );
}
