import { LessonLayout } from '../../components/layout';
import { Definition, Theorem, Example, Math, MathBlock } from '../../components/common';
import 'katex/dist/katex.min.css';

export default function Section20() {
  return (
    <LessonLayout sectionId={20}>
      <div className="space-y-8">
        {/* Introduction */}
        <section>
          <p className="text-lg text-dark-300 leading-relaxed">
            <strong>Free groups</strong> are the "most general" groups on a given set of generators—they
            impose no relations beyond the group axioms. They are fundamental in combinatorial
            group theory and topology.
          </p>
        </section>

        {/* Definition */}
        <section>
          <h3 className="text-xl font-semibold mb-4">Free Groups</h3>

          <Definition title="Free Group">
            <p>
              The <strong>free group</strong> <Math>{'F(S)'}</Math> on a set <Math>S</Math> is characterized by:
              for any group <Math>G</Math> and any function <Math>{'f: S \\to G'}</Math>,
              there exists a unique homomorphism <Math>{'\\phi: F(S) \\to G'}</Math> extending <Math>f</Math>.
            </p>
          </Definition>

          <Definition title="Words">
            <p>
              Elements of <Math>{'F(S)'}</Math> are equivalence classes of <strong>words</strong>—finite
              sequences of elements from <Math>S</Math> and their formal inverses <Math>{'S^{-1}'}</Math>.
            </p>
            <MathBlock>{'w = s_1^{\\epsilon_1} s_2^{\\epsilon_2} \\cdots s_n^{\\epsilon_n}, \\quad \\epsilon_i = \\pm 1'}</MathBlock>
          </Definition>

          <Example title="Words in F(a,b)">
            <div className="bg-dark-900 p-4 rounded">
              <p className="mb-2">Examples of words in <Math>{'F(\\{a,b\\})'}</Math>:</p>
              <ul className="list-disc list-inside text-dark-300 space-y-1">
                <li><Math>{'ab^2a^{-1}'}</Math> (= abba⁻¹)</li>
                <li><Math>{'a^3b^{-2}ab'}</Math></li>
                <li><Math>{'e'}</Math> (empty word)</li>
                <li><Math>{'aba^{-1}b^{-1}'}</Math> (commutator [a,b])</li>
              </ul>
            </div>
          </Example>
        </section>

        {/* Reduced Words */}
        <section>
          <h3 className="text-xl font-semibold mb-4">Reduced Words</h3>

          <Definition title="Reduced Word">
            <p>
              A word is <strong>reduced</strong> if it contains no consecutive pair <Math>{'ss^{-1}'}</Math>
              or <Math>{'s^{-1}s'}</Math>. Every word can be reduced by canceling such pairs.
            </p>
          </Definition>

          <Theorem title="Unique Reduced Representative">
            <p>
              Every element of <Math>{'F(S)'}</Math> has a unique reduced word representative.
              Two words represent the same element iff they reduce to the same reduced word.
            </p>
          </Theorem>

          <Example title="Reduction">
            <div className="bg-dark-900 p-4 rounded space-y-2">
              <p><Math>{'aba^{-1}ab^{-1}ba^{-1}'}</Math></p>
              <p className="text-dark-400">→ <Math>{'ab \\cdot \\cancel{a^{-1}a} \\cdot b^{-1}ba^{-1}'}</Math></p>
              <p className="text-dark-400">→ <Math>{'ab \\cdot \\cancel{b^{-1}b} \\cdot a^{-1}'}</Math></p>
              <p className="text-primary-400">→ <Math>{'aba^{-1}'}</Math> (reduced)</p>
            </div>
          </Example>
        </section>

        {/* Properties */}
        <section>
          <h3 className="text-xl font-semibold mb-4">Properties of Free Groups</h3>

          <div className="card">
            <h4 className="font-semibold mb-3">Key Properties</h4>
            <ul className="space-y-2 text-dark-300">
              <li>
                <Math>{'F(S)'}</Math> is generated by <Math>S</Math> with no relations
              </li>
              <li>
                <Math>{'|S| = 1'}</Math>: <Math>{'F(\\{a\\}) \\cong \\mathbb{Z}'}</Math>
              </li>
              <li>
                <Math>{'|S| \\geq 2'}</Math>: <Math>{'F(S)'}</Math> is nonabelian
              </li>
              <li>
                Free groups are torsion-free (no elements of finite order except <Math>e</Math>)
              </li>
              <li>
                Every subgroup of a free group is free (Nielsen-Schreier theorem)
              </li>
            </ul>
          </div>

          <Theorem title="Universal Property">
            <p>
              For any group <Math>G</Math> generated by <Math>S</Math>, there is a surjective homomorphism
              <Math>{'F(S) \\twoheadrightarrow G'}</Math>. Thus every group is a quotient of a free group.
            </p>
          </Theorem>
        </section>

        {/* Rank */}
        <section>
          <h3 className="text-xl font-semibold mb-4">Rank of Free Groups</h3>

          <Definition title="Rank">
            <p>
              The <strong>rank</strong> of a free group <Math>{'F(S)'}</Math> is <Math>{'|S|'}</Math>.
              This is an invariant (independent of generating set).
            </p>
          </Definition>

          <Example title="Free Groups by Rank">
            <div className="space-y-3">
              <div className="bg-dark-900 p-3 rounded">
                <p className="font-semibold text-primary-400">Rank 0</p>
                <p className="text-dark-300"><Math>{'F(\\emptyset) = \\{e\\}'}</Math>, the trivial group</p>
              </div>
              <div className="bg-dark-900 p-3 rounded">
                <p className="font-semibold text-primary-400">Rank 1</p>
                <p className="text-dark-300"><Math>{'F(a) \\cong \\mathbb{Z}'}</Math></p>
              </div>
              <div className="bg-dark-900 p-3 rounded">
                <p className="font-semibold text-primary-400">Rank 2</p>
                <p className="text-dark-300"><Math>{'F(a,b)'}</Math> — contains every countable group as subgroup!</p>
              </div>
            </div>
          </Example>
        </section>

        {/* Subgroups */}
        <section>
          <h3 className="text-xl font-semibold mb-4">Subgroups of Free Groups</h3>

          <Theorem title="Nielsen-Schreier Theorem">
            <p>
              Every subgroup of a free group is free.
            </p>
          </Theorem>

          <Theorem title="Schreier Index Formula">
            <p>
              If <Math>H</Math> is a subgroup of index <Math>n</Math> in a free group <Math>{'F_r'}</Math>
              of rank <Math>r</Math>, then <Math>H</Math> has rank:
            </p>
            <MathBlock>{'\\text{rank}(H) = n(r-1) + 1'}</MathBlock>
          </Theorem>

          <Example title="Commutator Subgroup of F₂">
            <p className="mb-3">
              The commutator subgroup <Math>{'[F_2, F_2]'}</Math> of the free group on 2 generators:
            </p>
            <div className="bg-dark-900 p-4 rounded">
              <p><Math>{'F_2/[F_2, F_2] \\cong \\mathbb{Z}^2'}</Math> (abelianization)</p>
              <p className="mt-2">Index: <Math>{'[F_2 : [F_2, F_2]] = \\infty'}</Math></p>
              <p className="text-dark-400 text-sm mt-2">
                <Math>{'[F_2, F_2]'}</Math> is free of infinite rank!
              </p>
            </div>
          </Example>
        </section>

        {/* Applications */}
        <section>
          <h3 className="text-xl font-semibold mb-4">Applications</h3>

          <div className="grid md:grid-cols-2 gap-4">
            <div className="card">
              <h4 className="font-semibold text-primary-400 mb-2">Topology</h4>
              <p className="text-dark-300 text-sm">
                The fundamental group <Math>{'\\pi_1'}</Math> of a wedge of <Math>n</Math> circles
                is <Math>{'F_n'}</Math>.
              </p>
            </div>
            <div className="card">
              <h4 className="font-semibold text-primary-400 mb-2">Group Presentations</h4>
              <p className="text-dark-300 text-sm">
                Every group is <Math>{'F(S)/N'}</Math> for some normal subgroup <Math>N</Math>
                (the relations).
              </p>
            </div>
            <div className="card">
              <h4 className="font-semibold text-primary-400 mb-2">Combinatorics</h4>
              <p className="text-dark-300 text-sm">
                Free groups model tree-like structures and branching processes.
              </p>
            </div>
            <div className="card">
              <h4 className="font-semibold text-primary-400 mb-2">Geometric Group Theory</h4>
              <p className="text-dark-300 text-sm">
                The Cayley graph of <Math>{'F_n'}</Math> is an infinite tree.
              </p>
            </div>
          </div>
        </section>

        {/* Summary */}
        <section className="card">
          <h3 className="text-xl font-semibold mb-4">Key Takeaways</h3>
          <ul className="space-y-2 text-dark-300">
            <li>
              Free groups impose no relations beyond group axioms.
            </li>
            <li>
              Elements are reduced words; the operation is concatenation + reduction.
            </li>
            <li>
              Every group is a quotient of a free group.
            </li>
            <li>
              <strong>Nielsen-Schreier:</strong> Subgroups of free groups are free.
            </li>
            <li>
              The rank-2 free group <Math>{'F_2'}</Math> contains all countable groups.
            </li>
          </ul>
        </section>
      </div>
    </LessonLayout>
  );
}
