import { LessonLayout } from '../../components/layout';
import { Definition, Theorem, Example, Math, MathBlock } from '../../components/common';
import 'katex/dist/katex.min.css';

export default function Section09() {
  return (
    <LessonLayout sectionId={9}>
      <div className="space-y-8">
        {/* Introduction */}
        <section>
          <p className="text-lg text-dark-300 leading-relaxed">
            The <strong>Fundamental Theorem of Finitely Generated Abelian Groups</strong> provides
            a complete classification: every such group is isomorphic to a direct product of cyclic
            groups. This powerful result tells us exactly what all finitely generated abelian groups look like.
          </p>
        </section>

        {/* Finitely Generated Groups */}
        <Definition title="Finitely Generated Group">
          <p>
            A group <Math>G</Math> is <strong>finitely generated</strong> if there exists a finite
            subset <Math>{'S = \\{g_1, g_2, ..., g_n\\}'}</Math> such that every element of <Math>G</Math>
            can be expressed as a product of elements from <Math>S</Math> and their inverses.
          </p>
          <MathBlock>{'G = \\langle g_1, g_2, ..., g_n \\rangle'}</MathBlock>
        </Definition>

        <Example title="Finitely Generated Examples">
          <div className="space-y-3">
            <div className="bg-dark-900 p-3 rounded">
              <p className="font-semibold text-primary-400"><Math>{'\\mathbb{Z}'}</Math></p>
              <p className="text-dark-300">Generated by <Math>{'{1}'}</Math> (or <Math>{'{-1}'}</Math>)</p>
            </div>
            <div className="bg-dark-900 p-3 rounded">
              <p className="font-semibold text-primary-400"><Math>{'\\mathbb{Z} \\times \\mathbb{Z}'}</Math></p>
              <p className="text-dark-300">Generated by <Math>{'{(1,0), (0,1)}'}</Math></p>
            </div>
            <div className="bg-dark-900 p-3 rounded">
              <p className="font-semibold text-primary-400"><Math>{'\\mathbb{Q}'}</Math> under addition</p>
              <p className="text-dark-300">NOT finitely generated (needs infinitely many fractions)</p>
            </div>
          </div>
        </Example>

        {/* Free Abelian Groups */}
        <section>
          <h3 className="text-xl font-semibold mb-4">Free Abelian Groups</h3>

          <Definition title="Free Abelian Group">
            <p>
              A <strong>free abelian group</strong> of rank <Math>n</Math> is isomorphic to:
            </p>
            <MathBlock>{'\\mathbb{Z}^n = \\underbrace{\\mathbb{Z} \\times \\mathbb{Z} \\times \\cdots \\times \\mathbb{Z}}_{n \\text{ copies}}'}</MathBlock>
            <p className="mt-2">
              Elements are <Math>n</Math>-tuples of integers with componentwise addition.
            </p>
          </Definition>

          <div className="card">
            <h4 className="font-semibold mb-3">Properties of <Math>{'\\mathbb{Z}^n'}</Math></h4>
            <ul className="space-y-2 text-dark-300">
              <li>
                Every element can be uniquely written as <Math>{'a_1 e_1 + a_2 e_2 + ... + a_n e_n'}</Math>
              </li>
              <li>
                The standard basis <Math>{'\\{e_1, ..., e_n\\}'}</Math> generates freely
              </li>
              <li>
                No relations except those forced by abelian group axioms
              </li>
              <li>
                The rank <Math>n</Math> is an invariant (well-defined)
              </li>
            </ul>
          </div>
        </section>

        {/* Fundamental Theorem */}
        <section>
          <h3 className="text-xl font-semibold mb-4">The Fundamental Theorem</h3>

          <Theorem title="Fundamental Theorem of Finitely Generated Abelian Groups">
            <p>
              Every finitely generated abelian group <Math>G</Math> is isomorphic to a direct product:
            </p>
            <MathBlock>{'G \\cong \\mathbb{Z}^r \\times \\mathbb{Z}_{n_1} \\times \\mathbb{Z}_{n_2} \\times \\cdots \\times \\mathbb{Z}_{n_k}'}</MathBlock>
            <p className="mt-2">
              where <Math>{'r \\geq 0'}</Math> and <Math>{'n_1 | n_2 | \\cdots | n_k'}</Math> (each divides the next).
            </p>
            <p className="mt-2">
              The number <Math>r</Math> is the <strong>free rank</strong> (or Betti number), and the
              <Math>{'n_i'}</Math> are the <strong>invariant factors</strong>.
            </p>
          </Theorem>

          <div className="callout-info">
            <p>
              <strong>Uniqueness:</strong> The decomposition is unique! Both <Math>r</Math> and the
              invariant factors <Math>{'n_1, ..., n_k'}</Math> are completely determined by <Math>G</Math>.
            </p>
          </div>
        </section>

        {/* Primary Decomposition */}
        <section>
          <h3 className="text-xl font-semibold mb-4">Primary Decomposition</h3>

          <Theorem title="Primary Decomposition">
            <p>
              Alternatively, every finitely generated abelian group is isomorphic to:
            </p>
            <MathBlock>{'G \\cong \\mathbb{Z}^r \\times \\mathbb{Z}_{p_1^{a_1}} \\times \\mathbb{Z}_{p_2^{a_2}} \\times \\cdots \\times \\mathbb{Z}_{p_m^{a_m}}'}</MathBlock>
            <p className="mt-2">
              where each <Math>{'p_i^{a_i}'}</Math> is a prime power. These are the <strong>elementary divisors</strong>.
            </p>
          </Theorem>

          <Example title="Z₁₂ Decomposition">
            <p className="mb-3">
              The group <Math>{'\\mathbb{Z}_{12}'}</Math> can be written:
            </p>
            <div className="space-y-2 bg-dark-900 p-4 rounded">
              <p><strong>Invariant factors:</strong> <Math>{'\\mathbb{Z}_{12}'}</Math></p>
              <p><strong>Elementary divisors:</strong> <Math>{'\\mathbb{Z}_4 \\times \\mathbb{Z}_3'}</Math></p>
              <p className="text-dark-400 mt-2">Since <Math>{'12 = 4 \\times 3'}</Math> and <Math>{'\\gcd(4,3) = 1'}</Math></p>
            </div>
          </Example>

          <Example title="Abelian Groups of Order 72">
            <p className="mb-3">
              Since <Math>{'72 = 8 \\times 9 = 2^3 \\times 3^2'}</Math>, the abelian groups of order 72 are:
            </p>
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-dark-700">
                    <th className="text-left p-2">Elementary Divisors</th>
                    <th className="text-left p-2">Invariant Factors</th>
                  </tr>
                </thead>
                <tbody className="text-dark-300">
                  <tr className="border-b border-dark-800">
                    <td className="p-2"><Math>{'\\mathbb{Z}_8 \\times \\mathbb{Z}_9'}</Math></td>
                    <td className="p-2"><Math>{'\\mathbb{Z}_{72}'}</Math></td>
                  </tr>
                  <tr className="border-b border-dark-800">
                    <td className="p-2"><Math>{'\\mathbb{Z}_8 \\times \\mathbb{Z}_3 \\times \\mathbb{Z}_3'}</Math></td>
                    <td className="p-2"><Math>{'\\mathbb{Z}_3 \\times \\mathbb{Z}_{24}'}</Math></td>
                  </tr>
                  <tr className="border-b border-dark-800">
                    <td className="p-2"><Math>{'\\mathbb{Z}_4 \\times \\mathbb{Z}_2 \\times \\mathbb{Z}_9'}</Math></td>
                    <td className="p-2"><Math>{'\\mathbb{Z}_2 \\times \\mathbb{Z}_{36}'}</Math></td>
                  </tr>
                  <tr className="border-b border-dark-800">
                    <td className="p-2"><Math>{'\\mathbb{Z}_4 \\times \\mathbb{Z}_2 \\times \\mathbb{Z}_3 \\times \\mathbb{Z}_3'}</Math></td>
                    <td className="p-2"><Math>{'\\mathbb{Z}_6 \\times \\mathbb{Z}_{12}'}</Math></td>
                  </tr>
                  <tr className="border-b border-dark-800">
                    <td className="p-2"><Math>{'\\mathbb{Z}_2 \\times \\mathbb{Z}_2 \\times \\mathbb{Z}_2 \\times \\mathbb{Z}_9'}</Math></td>
                    <td className="p-2"><Math>{'\\mathbb{Z}_2 \\times \\mathbb{Z}_2 \\times \\mathbb{Z}_{18}'}</Math></td>
                  </tr>
                  <tr>
                    <td className="p-2"><Math>{'\\mathbb{Z}_2 \\times \\mathbb{Z}_2 \\times \\mathbb{Z}_2 \\times \\mathbb{Z}_3 \\times \\mathbb{Z}_3'}</Math></td>
                    <td className="p-2"><Math>{'\\mathbb{Z}_6 \\times \\mathbb{Z}_6 \\times \\mathbb{Z}_2'}</Math></td>
                  </tr>
                </tbody>
              </table>
            </div>
            <p className="text-dark-400 text-sm mt-2">
              There are exactly 6 non-isomorphic abelian groups of order 72.
            </p>
          </Example>
        </section>

        {/* Computing the Decomposition */}
        <section>
          <h3 className="text-xl font-semibold mb-4">Computing Decompositions</h3>

          <div className="card">
            <h4 className="font-semibold mb-3">Converting Between Forms</h4>
            <div className="space-y-4 text-dark-300">
              <div>
                <p className="font-semibold text-primary-400">Invariant → Elementary:</p>
                <p>Factor each invariant factor into prime powers</p>
              </div>
              <div>
                <p className="font-semibold text-primary-400">Elementary → Invariant:</p>
                <p>Group prime powers, multiply using CRT compatibility</p>
              </div>
            </div>
          </div>

          <Example title="Converting Forms">
            <p className="mb-3">
              Given elementary divisors <Math>{'\\mathbb{Z}_4 \\times \\mathbb{Z}_2 \\times \\mathbb{Z}_9 \\times \\mathbb{Z}_3'}</Math>:
            </p>
            <div className="bg-dark-900 p-4 rounded space-y-2">
              <p>Powers of 2: 4, 2</p>
              <p>Powers of 3: 9, 3</p>
              <p className="mt-2">
                Invariant factors: <Math>{'\\mathbb{Z}_{2 \\cdot 3} \\times \\mathbb{Z}_{4 \\cdot 9} = \\mathbb{Z}_6 \\times \\mathbb{Z}_{36}'}</Math>
              </p>
            </div>
          </Example>
        </section>

        {/* Torsion Subgroup */}
        <section>
          <h3 className="text-xl font-semibold mb-4">Torsion Elements</h3>

          <Definition title="Torsion Subgroup">
            <p>
              The <strong>torsion subgroup</strong> <Math>{'T(G)'}</Math> of an abelian group <Math>G</Math>
              consists of all elements of finite order:
            </p>
            <MathBlock>{'T(G) = \\{g \\in G : ng = 0 \\text{ for some } n > 0\\}'}</MathBlock>
          </Definition>

          <div className="card">
            <p className="text-dark-300">
              For a finitely generated abelian group <Math>{'G \\cong \\mathbb{Z}^r \\times T'}</Math>:
            </p>
            <ul className="list-disc list-inside mt-2 space-y-1 text-dark-300">
              <li><Math>{'\\mathbb{Z}^r'}</Math> is the <strong>free part</strong> (torsion-free)</li>
              <li><Math>T</Math> is the <strong>torsion part</strong> (finite)</li>
              <li>The group is <strong>torsion-free</strong> if <Math>{'T = \\{0\\}'}</Math></li>
            </ul>
          </div>
        </section>

        {/* Applications */}
        <section>
          <h3 className="text-xl font-semibold mb-4">Applications</h3>

          <div className="grid md:grid-cols-2 gap-4">
            <div className="card">
              <h4 className="font-semibold mb-2">Counting Subgroups</h4>
              <p className="text-dark-300 text-sm">
                The structure theorem helps count subgroups of finite abelian groups.
              </p>
            </div>
            <div className="card">
              <h4 className="font-semibold mb-2">Module Theory</h4>
              <p className="text-dark-300 text-sm">
                Abelian groups are <Math>{'\\mathbb{Z}'}</Math>-modules; this theorem is a special case
                of structure theorems for modules over PIDs.
              </p>
            </div>
            <div className="card">
              <h4 className="font-semibold mb-2">Algebraic Topology</h4>
              <p className="text-dark-300 text-sm">
                Homology groups are finitely generated abelian groups; this theorem classifies them.
              </p>
            </div>
            <div className="card">
              <h4 className="font-semibold mb-2">Number Theory</h4>
              <p className="text-dark-300 text-sm">
                Class groups of number fields and unit groups are finitely generated abelian.
              </p>
            </div>
          </div>
        </section>

        {/* Summary */}
        <section className="card">
          <h3 className="text-xl font-semibold mb-4">Key Takeaways</h3>
          <ul className="space-y-2 text-dark-300">
            <li>
              Every finitely generated abelian group decomposes as <Math>{'\\mathbb{Z}^r \\times'}</Math> (finite torsion).
            </li>
            <li>
              The decomposition is unique up to isomorphism.
            </li>
            <li>
              Invariant factors form a divisibility chain; elementary divisors are prime powers.
            </li>
            <li>
              The two forms are equivalent and can be converted between.
            </li>
            <li>
              This classifies all finite abelian groups completely.
            </li>
          </ul>
        </section>
      </div>
    </LessonLayout>
  );
}
