import { LessonLayout } from '../../components/layout';
import { Definition, Theorem, Example, Math, MathBlock } from '../../components/common';
import 'katex/dist/katex.min.css';

export default function Section44() {
  return (
    <LessonLayout sectionId={44}>
      <div className="space-y-8">
        {/* Introduction */}
        <section>
          <p className="text-lg text-dark-300 leading-relaxed">
            <strong>Splitting fields</strong> are the minimal extensions where a polynomial
            factors completely into linear factors. They are the natural setting for studying
            the roots of polynomials.
          </p>
        </section>

        {/* Definition */}
        <section>
          <h3 className="text-xl font-semibold mb-4">Splitting Fields</h3>

          <Definition title="Splits">
            <p>
              A polynomial <Math>{'f(x) \\in F[x]'}</Math> <strong>splits</strong> over <Math>E</Math>
              if it factors as:
            </p>
            <MathBlock>{'f(x) = a(x - \\alpha_1)(x - \\alpha_2)\\cdots(x - \\alpha_n)'}</MathBlock>
            <p className="mt-2">where all <Math>{'\\alpha_i \\in E'}</Math>.</p>
          </Definition>

          <Definition title="Splitting Field">
            <p>
              A <strong>splitting field</strong> for <Math>{'f(x) \\in F[x]'}</Math> is an extension
              <Math>E</Math> of <Math>F</Math> such that:
            </p>
            <ul className="list-disc list-inside mt-2 space-y-1">
              <li><Math>f</Math> splits over <Math>E</Math></li>
              <li><Math>E</Math> is generated by the roots: <Math>{'E = F(\\alpha_1, ..., \\alpha_n)'}</Math></li>
            </ul>
          </Definition>

          <Example title="Splitting Fields">
            <div className="space-y-3">
              <div className="bg-dark-900 p-3 rounded">
                <p className="font-semibold text-primary-400"><Math>{'x^2 - 2'}</Math> over <Math>{'\\mathbb{Q}'}</Math></p>
                <p className="text-dark-300">Splitting field: <Math>{'\\mathbb{Q}(\\sqrt{2})'}</Math></p>
                <p className="text-dark-400 text-sm">Roots: <Math>{'\\pm\\sqrt{2}'}</Math></p>
              </div>
              <div className="bg-dark-900 p-3 rounded">
                <p className="font-semibold text-primary-400"><Math>{'x^3 - 2'}</Math> over <Math>{'\\mathbb{Q}'}</Math></p>
                <p className="text-dark-300">Splitting field: <Math>{'\\mathbb{Q}(\\sqrt[3]{2}, \\omega)'}</Math></p>
                <p className="text-dark-400 text-sm">
                  Roots: <Math>{'\\sqrt[3]{2}, \\sqrt[3]{2}\\omega, \\sqrt[3]{2}\\omega^2'}</Math>
                  where <Math>{'\\omega = e^{2\\pi i/3}'}</Math>
                </p>
              </div>
              <div className="bg-dark-900 p-3 rounded">
                <p className="font-semibold text-primary-400"><Math>{'x^4 - 1'}</Math> over <Math>{'\\mathbb{Q}'}</Math></p>
                <p className="text-dark-300">Splitting field: <Math>{'\\mathbb{Q}(i)'}</Math></p>
                <p className="text-dark-400 text-sm">Roots: <Math>{'1, -1, i, -i'}</Math></p>
              </div>
            </div>
          </Example>
        </section>

        {/* Existence and Uniqueness */}
        <section>
          <h3 className="text-xl font-semibold mb-4">Existence and Uniqueness</h3>

          <Theorem title="Existence of Splitting Fields">
            <p>
              Every polynomial <Math>{'f(x) \\in F[x]'}</Math> has a splitting field over <Math>F</Math>.
            </p>
          </Theorem>

          <Theorem title="Uniqueness">
            <p>
              Any two splitting fields for <Math>{'f(x) \\in F[x]'}</Math> are isomorphic over <Math>F</Math>.
            </p>
          </Theorem>

          <Theorem title="Degree Bound">
            <p>
              If <Math>{'\\deg(f) = n'}</Math>, then:
            </p>
            <MathBlock>{'[E:F] \\leq n!'}</MathBlock>
            <p className="mt-2">Equality holds when <Math>f</Math> is irreducible with Galois group <Math>S_n</Math>.</p>
          </Theorem>

          <Example title="Degree of Splitting Field">
            <div className="bg-dark-900 p-4 rounded">
              <p><Math>{'f(x) = x^3 - 2'}</Math> over <Math>{'\\mathbb{Q}'}</Math></p>
              <p className="mt-2">
                <Math>{'[\\mathbb{Q}(\\sqrt[3]{2}):\\mathbb{Q}] = 3'}</Math> (not yet split)
              </p>
              <p>
                <Math>{'[\\mathbb{Q}(\\sqrt[3]{2}, \\omega):\\mathbb{Q}(\\sqrt[3]{2})] = 2'}</Math>
              </p>
              <p className="text-primary-400 mt-2">
                Total: <Math>{'[\\mathbb{Q}(\\sqrt[3]{2}, \\omega):\\mathbb{Q}] = 6'}</Math>
              </p>
            </div>
          </Example>
        </section>

        {/* Galois Groups of Splitting Fields */}
        <section>
          <h3 className="text-xl font-semibold mb-4">Galois Groups and Permutations</h3>

          <Theorem title="Galois Group as Permutation Group">
            <p>
              If <Math>E</Math> is the splitting field of <Math>f</Math> over <Math>F</Math>, then
              <Math>{'\\text{Gal}(E/F)'}</Math> acts faithfully on the roots, giving an embedding:
            </p>
            <MathBlock>{'\\text{Gal}(E/F) \\hookrightarrow S_n'}</MathBlock>
          </Theorem>

          <Example title="Galois Group Computation">
            <div className="space-y-3">
              <div className="bg-dark-900 p-3 rounded">
                <p className="font-semibold text-primary-400"><Math>{'x^2 - 2'}</Math></p>
                <p className="text-dark-300">
                  <Math>{'\\text{Gal}(\\mathbb{Q}(\\sqrt{2})/\\mathbb{Q}) \\cong \\mathbb{Z}_2 \\subseteq S_2'}</Math>
                </p>
              </div>
              <div className="bg-dark-900 p-3 rounded">
                <p className="font-semibold text-primary-400"><Math>{'x^3 - 2'}</Math></p>
                <p className="text-dark-300">
                  <Math>{'\\text{Gal}(\\mathbb{Q}(\\sqrt[3]{2}, \\omega)/\\mathbb{Q}) \\cong S_3'}</Math>
                </p>
              </div>
              <div className="bg-dark-900 p-3 rounded">
                <p className="font-semibold text-primary-400"><Math>{'x^4 - 2'}</Math></p>
                <p className="text-dark-300">
                  <Math>{'\\text{Gal}(\\mathbb{Q}(\\sqrt[4]{2}, i)/\\mathbb{Q}) \\cong D_4'}</Math>
                </p>
              </div>
            </div>
          </Example>
        </section>

        {/* Normal Extensions */}
        <section>
          <h3 className="text-xl font-semibold mb-4">Normal Extensions</h3>

          <Definition title="Normal Extension">
            <p>
              An algebraic extension <Math>{'E/F'}</Math> is <strong>normal</strong> if every
              irreducible polynomial in <Math>{'F[x]'}</Math> with a root in <Math>E</Math>
              splits completely in <Math>E</Math>.
            </p>
          </Definition>

          <Theorem title="Normal = Splitting Field">
            <p>
              A finite extension <Math>{'E/F'}</Math> is normal iff <Math>E</Math> is the splitting
              field of some polynomial over <Math>F</Math>.
            </p>
          </Theorem>
        </section>

        {/* Summary */}
        <section className="card">
          <h3 className="text-xl font-semibold mb-4">Key Takeaways</h3>
          <ul className="space-y-2 text-dark-300">
            <li>
              <strong>Splitting field:</strong> minimal extension where polynomial factors completely.
            </li>
            <li>
              Splitting fields exist and are unique up to isomorphism.
            </li>
            <li>
              <Math>{'[E:F] \\leq n!'}</Math> for degree <Math>n</Math> polynomial.
            </li>
            <li>
              Galois group embeds into <Math>S_n</Math> by permuting roots.
            </li>
            <li>
              <strong>Normal extension:</strong> = splitting field (for finite extensions).
            </li>
          </ul>
        </section>
      </div>
    </LessonLayout>
  );
}
