import { useState } from 'react';

type Difficulty = 'easy' | 'medium' | 'hard';

interface MultipleChoiceQuestion {
  type: string;
  responseType: 'multiple_choice';
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
}

interface FreeResponseQuestion {
  type: string;
  responseType: 'free_response';
  question: string;
  correctAnswer: string;
  acceptedAnswers: string[];
  explanation: string;
}

type Question = MultipleChoiceQuestion | FreeResponseQuestion;

function shuffle<T>(array: T[]): T[] {
  const arr = [...array];
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

function randomChoice<T>(array: T[]): T {
  return array[Math.floor(Math.random() * array.length)];
}

// Free abelian group definition
function generateDefinitionQuestion(_difficulty: Difficulty): MultipleChoiceQuestion {
  const options = shuffle([
    'An abelian group with a basis (linearly independent generating set)',
    'Any abelian group',
    'An abelian group with finitely many elements',
    'An abelian group where every element has finite order'
  ]);

  return {
    type: 'definition',
    responseType: 'multiple_choice',
    question: 'What is a free abelian group?',
    options,
    correctIndex: options.indexOf('An abelian group with a basis (linearly independent generating set)'),
    explanation: 'A free abelian group is one with a basis: a generating set where every element can be uniquely written as a finite ℤ-linear combination of basis elements.'
  };
}

// Rank questions
function generateRankQuestion(difficulty: Difficulty): FreeResponseQuestion {
  const scenarios = difficulty === 'easy' ? [
    { group: 'ℤ', rank: '1', why: 'ℤ is free abelian with basis {1}' },
    { group: 'ℤ × ℤ', rank: '2', why: 'ℤ² has basis {(1,0), (0,1)}' },
    { group: 'ℤ × ℤ × ℤ', rank: '3', why: 'ℤ³ has basis {e₁, e₂, e₃}' },
  ] : difficulty === 'medium' ? [
    { group: 'ℤⁿ', rank: 'n', why: 'ℤⁿ has rank n, basis is the standard basis' },
    { group: '2ℤ (even integers)', rank: '1', why: '2ℤ ≅ ℤ via n ↦ 2n' },
  ] : [
    { group: 'ℤ × ℤ₂', rank: '1', why: 'ℤ₂ is torsion, only ℤ contributes to free rank' },
    { group: 'the subgroup of ℤ² generated by (2,0) and (0,3)', rank: '2', why: 'generates a sublattice of rank 2' },
  ];

  const scenario = randomChoice(scenarios);
  return {
    type: 'rank',
    responseType: 'free_response',
    question: `What is the rank (free rank) of ${scenario.group}?`,
    correctAnswer: scenario.rank,
    acceptedAnswers: [scenario.rank],
    explanation: scenario.why
  };
}

// Is it free abelian?
function generateIsFreeQuestion(difficulty: Difficulty): MultipleChoiceQuestion {
  const scenarios = difficulty === 'easy' ? [
    { group: 'ℤ', isFree: true, why: 'ℤ is the prototype free abelian group' },
    { group: 'ℤₙ (n > 1)', isFree: false, why: 'has torsion: every nonzero element has finite order' },
    { group: 'ℚ', isFree: false, why: 'not finitely generated as abelian group' },
  ] : difficulty === 'medium' ? [
    { group: 'ℤ × ℤ', isFree: true, why: 'direct product of free abelian groups is free abelian' },
    { group: 'ℤ × ℤ₂', isFree: false, why: 'contains torsion element (0, 1)' },
    { group: 'ℚ/ℤ', isFree: false, why: 'every element has finite order (torsion group)' },
  ] : [
    { group: 'subgroup of ℤⁿ', isFree: true, why: 'subgroups of free abelian groups are free abelian' },
    { group: 'ℤ[1/p] = {a/pⁿ : a ∈ ℤ, n ≥ 0}', isFree: false, why: 'not finitely generated' },
  ];

  const scenario = randomChoice(scenarios);
  return {
    type: 'is_free',
    responseType: 'multiple_choice',
    question: `Is ${scenario.group} a free abelian group?`,
    options: ['Yes', 'No'],
    correctIndex: scenario.isFree ? 0 : 1,
    explanation: scenario.isFree ? `Yes: ${scenario.why}.` : `No: ${scenario.why}.`
  };
}

// Subgroups of free abelian groups
function generateSubgroupQuestion(difficulty: Difficulty): MultipleChoiceQuestion {
  const scenarios = difficulty === 'easy' ? [
    {
      statement: 'Every subgroup of ℤ is of the form nℤ for some n ≥ 0',
      correct: true,
      why: 'Subgroups of ℤ are cyclic: {0} or nℤ'
    },
  ] : difficulty === 'medium' ? [
    {
      statement: 'Every subgroup of a free abelian group is free abelian',
      correct: true,
      why: 'Fundamental theorem: subgroups of ℤⁿ are free abelian of rank ≤ n'
    },
    {
      statement: 'A subgroup of ℤⁿ has rank exactly n',
      correct: false,
      why: 'False: the rank can be any k ≤ n'
    },
  ] : [
    {
      statement: 'If H ⊆ ℤⁿ has rank n, then ℤⁿ/H is finite',
      correct: true,
      why: 'rank(H) = n means H spans ℚⁿ, so quotient is torsion'
    },
    {
      statement: 'The index [ℤⁿ : H] equals |det(basis matrix of H)|',
      correct: true,
      why: 'For a sublattice of full rank, index = |determinant|'
    },
  ];

  const scenario = randomChoice(scenarios);
  return {
    type: 'subgroup',
    responseType: 'multiple_choice',
    question: `True or False: ${scenario.statement}`,
    options: ['True', 'False'],
    correctIndex: scenario.correct ? 0 : 1,
    explanation: scenario.why
  };
}

// Basis change
function generateBasisQuestion(difficulty: Difficulty): MultipleChoiceQuestion {
  const scenarios = difficulty === 'easy' ? [
    {
      statement: 'Any two bases of a free abelian group have the same size',
      correct: true,
      why: 'The rank (basis size) is an invariant'
    },
  ] : difficulty === 'medium' ? [
    {
      statement: '{(1,1), (1,-1)} is a basis for ℤ²',
      correct: false,
      why: 'det = -2, not ±1, so doesn\'t span all of ℤ²'
    },
    {
      statement: '{(1,0), (1,1)} is a basis for ℤ²',
      correct: true,
      why: 'det = 1, and both are in ℤ², so this is a basis'
    },
  ] : [
    {
      statement: 'Two matrices give bases for the same sublattice iff they differ by a unimodular matrix',
      correct: true,
      why: 'Unimodular matrices (det ±1) are exactly the invertible integer matrices'
    },
  ];

  const scenario = randomChoice(scenarios);
  return {
    type: 'basis',
    responseType: 'multiple_choice',
    question: `True or False: ${scenario.statement}`,
    options: ['True', 'False'],
    correctIndex: scenario.correct ? 0 : 1,
    explanation: scenario.why
  };
}

// Quotient groups
function generateQuotientQuestion(difficulty: Difficulty): FreeResponseQuestion {
  const scenarios = difficulty === 'easy' ? [
    { quotient: 'ℤ/3ℤ', order: '3', why: 'ℤ/3ℤ = {0, 1, 2} has 3 elements' },
    { quotient: 'ℤ²/ℤ²', order: '1', why: 'trivial quotient' },
  ] : difficulty === 'medium' ? [
    { quotient: 'ℤ² modulo sublattice spanned by (2,0) and (0,3)', order: '6', why: '|det| = 6' },
    { quotient: 'ℤ² modulo sublattice spanned by (1,1) and (1,-1)', order: '2', why: '|det| = |-2| = 2' },
  ] : [
    { quotient: 'ℤ³ modulo sublattice spanned by (2,0,0), (0,3,0), (0,0,5)', order: '30', why: '|det| = 2·3·5 = 30' },
  ];

  const scenario = randomChoice(scenarios);
  return {
    type: 'quotient',
    responseType: 'free_response',
    question: `What is the order of ${scenario.quotient}?`,
    correctAnswer: scenario.order,
    acceptedAnswers: [scenario.order],
    explanation: scenario.why
  };
}

function generateQuestion(difficulty: Difficulty): Question {
  const generators = [
    generateDefinitionQuestion,
    generateRankQuestion,
    generateIsFreeQuestion,
    generateSubgroupQuestion,
    generateBasisQuestion,
    generateQuotientQuestion,
  ];

  return randomChoice(generators)(difficulty);
}

function generateQuiz(difficulty: Difficulty): Question[] {
  const questions: Question[] = [];
  const usedTypes = new Set<string>();

  while (questions.length < 5) {
    const question = generateQuestion(difficulty);
    if (!usedTypes.has(question.type)) {
      usedTypes.add(question.type);
      questions.push(question);
    }
  }

  return questions;
}

export function FreeAbelianQuiz() {
  const [difficulty, setDifficulty] = useState<Difficulty | null>(null);
  const [questions, setQuestions] = useState<Question[]>([]);
  const [currentQuestion, setCurrentQuestion] = useState(0);
  const [selectedAnswer, setSelectedAnswer] = useState<number | null>(null);
  const [textAnswer, setTextAnswer] = useState('');
  const [showResult, setShowResult] = useState(false);
  const [score, setScore] = useState(0);
  const [quizComplete, setQuizComplete] = useState(false);

  const startQuiz = (diff: Difficulty) => {
    setDifficulty(diff);
    setQuestions(generateQuiz(diff));
    setCurrentQuestion(0);
    setSelectedAnswer(null);
    setTextAnswer('');
    setShowResult(false);
    setScore(0);
    setQuizComplete(false);
  };

  const checkAnswer = () => {
    const question = questions[currentQuestion];
    let isCorrect = false;

    if (question.responseType === 'multiple_choice') {
      isCorrect = selectedAnswer === question.correctIndex;
    } else {
      const normalizedAnswer = textAnswer.trim().toLowerCase();
      isCorrect = question.acceptedAnswers.some(
        ans => ans.toLowerCase() === normalizedAnswer
      );
    }

    if (isCorrect) setScore(score + 1);
    setShowResult(true);
  };

  const nextQuestion = () => {
    if (currentQuestion + 1 >= questions.length) {
      setQuizComplete(true);
    } else {
      setCurrentQuestion(currentQuestion + 1);
      setSelectedAnswer(null);
      setTextAnswer('');
      setShowResult(false);
    }
  };

  if (!difficulty) {
    return (
      <div className="my-8 p-6 bg-gray-900 rounded-xl border border-purple-500/30">
        <h3 className="text-xl font-bold text-purple-300 mb-4">Free Abelian Groups Quiz</h3>
        <p className="text-gray-300 mb-4">Test your understanding of free abelian groups, rank, and lattices!</p>
        <div className="flex gap-4 flex-wrap">
          {(['easy', 'medium', 'hard'] as Difficulty[]).map((diff) => (
            <button
              key={diff}
              onClick={() => startQuiz(diff)}
              className={`px-6 py-2 rounded-lg font-medium transition-all ${
                diff === 'easy' ? 'bg-green-600 hover:bg-green-500' :
                diff === 'medium' ? 'bg-yellow-600 hover:bg-yellow-500' :
                'bg-red-600 hover:bg-red-500'
              }`}
            >
              {diff.charAt(0).toUpperCase() + diff.slice(1)}
            </button>
          ))}
        </div>
      </div>
    );
  }

  if (quizComplete) {
    return (
      <div className="my-8 p-6 bg-gray-900 rounded-xl border border-purple-500/30">
        <h3 className="text-xl font-bold text-purple-300 mb-4">Quiz Complete!</h3>
        <p className="text-2xl text-white mb-4">
          Score: {score}/{questions.length} ({Math.round(score/questions.length * 100)}%)
        </p>
        <button
          onClick={() => setDifficulty(null)}
          className="px-6 py-2 bg-purple-600 hover:bg-purple-500 rounded-lg font-medium transition-all"
        >
          Try Again
        </button>
      </div>
    );
  }

  const question = questions[currentQuestion];

  return (
    <div className="my-8 p-6 bg-gray-900 rounded-xl border border-purple-500/30">
      <div className="flex justify-between items-center mb-4">
        <h3 className="text-lg font-bold text-purple-300">
          Question {currentQuestion + 1}/{questions.length}
        </h3>
        <span className="text-gray-400 capitalize">{difficulty}</span>
      </div>

      <p className="text-white text-lg mb-6">{question.question}</p>

      {question.responseType === 'multiple_choice' ? (
        <div className="space-y-3">
          {question.options.map((option, index) => (
            <button
              key={index}
              onClick={() => !showResult && setSelectedAnswer(index)}
              disabled={showResult}
              className={`w-full text-left p-4 rounded-lg border transition-all ${
                showResult
                  ? index === question.correctIndex
                    ? 'bg-green-600/30 border-green-500'
                    : index === selectedAnswer
                    ? 'bg-red-600/30 border-red-500'
                    : 'bg-gray-800 border-gray-600'
                  : selectedAnswer === index
                  ? 'bg-purple-600/30 border-purple-500'
                  : 'bg-gray-800 border-gray-600 hover:border-purple-500'
              }`}
            >
              {option}
            </button>
          ))}
        </div>
      ) : (
        <input
          type="text"
          value={textAnswer}
          onChange={(e) => setTextAnswer(e.target.value)}
          disabled={showResult}
          placeholder="Enter your answer..."
          className="w-full p-4 bg-gray-800 border border-gray-600 rounded-lg text-white focus:border-purple-500 focus:outline-none"
        />
      )}

      {showResult && (
        <div className={`mt-4 p-4 rounded-lg ${
          (question.responseType === 'multiple_choice' && selectedAnswer === question.correctIndex) ||
          (question.responseType === 'free_response' && question.acceptedAnswers.some(a => a.toLowerCase() === textAnswer.trim().toLowerCase()))
            ? 'bg-green-600/20 border border-green-500'
            : 'bg-red-600/20 border border-red-500'
        }`}>
          <p className="text-gray-200">{question.explanation}</p>
        </div>
      )}

      <div className="mt-6 flex justify-end">
        {!showResult ? (
          <button
            onClick={checkAnswer}
            disabled={question.responseType === 'multiple_choice' ? selectedAnswer === null : !textAnswer.trim()}
            className="px-6 py-2 bg-purple-600 hover:bg-purple-500 disabled:bg-gray-600 disabled:cursor-not-allowed rounded-lg font-medium transition-all"
          >
            Check Answer
          </button>
        ) : (
          <button
            onClick={nextQuestion}
            className="px-6 py-2 bg-purple-600 hover:bg-purple-500 rounded-lg font-medium transition-all"
          >
            {currentQuestion + 1 >= questions.length ? 'See Results' : 'Next Question'}
          </button>
        )}
      </div>
    </div>
  );
}
