import { useState } from 'react';

type Difficulty = 'easy' | 'medium' | 'hard';

interface MultipleChoiceQuestion {
  type: string;
  responseType: 'multiple_choice';
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
}

interface FreeResponseQuestion {
  type: string;
  responseType: 'free_response';
  question: string;
  correctAnswer: string;
  acceptedAnswers: string[];
  explanation: string;
}

type Question = MultipleChoiceQuestion | FreeResponseQuestion;

function shuffle<T>(array: T[]): T[] {
  const arr = [...array];
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

function randomChoice<T>(array: T[]): T {
  return array[Math.floor(Math.random() * array.length)];
}

// Free group definition
function generateDefinitionQuestion(_difficulty: Difficulty): MultipleChoiceQuestion {
  const options = shuffle([
    'A group where the only relations are the group axioms',
    'An abelian group with no relations',
    'Any group with a finite generating set',
    'A group where every element has finite order'
  ]);

  return {
    type: 'definition',
    responseType: 'multiple_choice',
    question: 'What is a free group?',
    options,
    correctIndex: options.indexOf('A group where the only relations are the group axioms'),
    explanation: 'A free group F(S) on set S has no relations beyond xx⁻¹ = e. Every element is a unique reduced word in S ∪ S⁻¹.'
  };
}

// Word reduction
function generateReductionQuestion(difficulty: Difficulty): FreeResponseQuestion {
  const scenarios = difficulty === 'easy' ? [
    { word: 'aba⁻¹', reduced: 'aba⁻¹', why: 'Already reduced (no adjacent inverses)' },
    { word: 'aa⁻¹b', reduced: 'b', why: 'aa⁻¹ = e cancels' },
    { word: 'ab⁻¹ba', reduced: 'a²', why: 'b⁻¹b = e cancels, leaving aa = a²' },
  ] : difficulty === 'medium' ? [
    { word: 'aba⁻¹b⁻¹', reduced: 'aba⁻¹b⁻¹', why: 'This is the commutator [a,b], already reduced' },
    { word: 'a²b⁻¹ba⁻¹', reduced: 'a', why: 'b⁻¹b cancels, then aa·a⁻¹ = a' },
  ] : [
    { word: 'abab⁻¹a⁻¹b⁻¹', reduced: 'abab⁻¹a⁻¹b⁻¹', why: 'No adjacent inverse pairs, already reduced' },
    { word: '(aba⁻¹)b⁻¹(aba⁻¹)⁻¹b', reduced: '[aba⁻¹, b]', why: 'This is the commutator of aba⁻¹ and b' },
  ];

  const scenario = randomChoice(scenarios);
  return {
    type: 'reduction',
    responseType: 'free_response',
    question: `In the free group F(a,b), what is the reduced form of ${scenario.word}?`,
    correctAnswer: scenario.reduced,
    acceptedAnswers: [scenario.reduced],
    explanation: scenario.why
  };
}

// Properties of free groups
function generatePropertyQuestion(difficulty: Difficulty): MultipleChoiceQuestion {
  const scenarios = difficulty === 'easy' ? [
    { statement: 'The free group on one generator is isomorphic to ℤ', correct: true, why: 'F(a) = {..., a⁻², a⁻¹, e, a, a², ...} ≅ ℤ' },
    { statement: 'Free groups are always abelian', correct: false, why: 'F(a,b) is non-abelian: ab ≠ ba as words' },
  ] : difficulty === 'medium' ? [
    { statement: 'Free groups are torsion-free (no elements of finite order except e)', correct: true, why: 'No word aⁿ = e unless a = e in a free group' },
    { statement: 'Every group is a quotient of some free group', correct: true, why: 'Every group G = F(S)/N for some generators S and relations N' },
  ] : [
    { statement: 'Subgroups of free groups are free', correct: true, why: 'Nielsen-Schreier theorem: every subgroup of a free group is free' },
    { statement: 'F(a,b) contains a copy of F(a,b,c)', correct: true, why: 'F₂ contains free groups of any countable rank' },
  ];

  const scenario = randomChoice(scenarios);
  return {
    type: 'property',
    responseType: 'multiple_choice',
    question: `True or False: ${scenario.statement}`,
    options: ['True', 'False'],
    correctIndex: scenario.correct ? 0 : 1,
    explanation: scenario.why
  };
}

// Universal property
function generateUniversalQuestion(_difficulty: Difficulty): MultipleChoiceQuestion {
  const options = shuffle([
    'Any function S → G extends uniquely to a homomorphism F(S) → G',
    'F(S) is the largest group generated by S',
    'F(S) contains every group generated by S as a subgroup',
    'Every homomorphism from F(S) is injective'
  ]);

  return {
    type: 'universal',
    responseType: 'multiple_choice',
    question: 'What is the universal property of the free group F(S)?',
    options,
    correctIndex: options.indexOf('Any function S → G extends uniquely to a homomorphism F(S) → G'),
    explanation: 'The universal property: any set map f: S → G to a group G extends uniquely to a group homomorphism F(S) → G.'
  };
}

// Rank of free groups
function generateRankQuestion(difficulty: Difficulty): MultipleChoiceQuestion {
  const scenarios = difficulty === 'easy' ? [
    { statement: 'F(a) and F(b) are isomorphic', correct: true, why: 'Both are free on one generator, so F(a) ≅ F(b) ≅ ℤ' },
    { statement: 'F(a,b) ≅ F(c)', correct: false, why: 'Different ranks: F₂ ≇ F₁ (F₂ is non-abelian)' },
  ] : difficulty === 'medium' ? [
    { statement: 'Two free groups are isomorphic iff they have the same rank', correct: true, why: 'Rank is an isomorphism invariant for free groups' },
    { statement: 'F(a,b) has uncountably many elements', correct: true, why: 'There are infinitely many reduced words of each length' },
  ] : [
    { statement: 'A subgroup of F₂ of index n has rank 1 + n(2-1) = n + 1', correct: true, why: 'Schreier formula: rank = 1 + (rank-1)·index' },
    { statement: 'F₂ contains subgroups of every finite rank', correct: true, why: 'By Schreier formula, index n subgroup has rank n+1' },
  ];

  const scenario = randomChoice(scenarios);
  return {
    type: 'rank',
    responseType: 'multiple_choice',
    question: `True or False: ${scenario.statement}`,
    options: ['True', 'False'],
    correctIndex: scenario.correct ? 0 : 1,
    explanation: scenario.why
  };
}

// Cayley graph
function generateCayleyQuestion(difficulty: Difficulty): MultipleChoiceQuestion {
  const scenarios = difficulty === 'easy' ? [
    {
      question: 'What is the Cayley graph of ℤ with generator {1}?',
      answer: 'An infinite line (path graph)',
      why: 'Each integer n connects to n±1'
    },
  ] : difficulty === 'medium' ? [
    {
      question: 'What is the Cayley graph of F(a,b)?',
      answer: 'An infinite 4-regular tree',
      why: 'Each vertex has 4 neighbors: a, a⁻¹, b, b⁻¹'
    },
  ] : [
    {
      question: 'The Cayley graph of F(a) is...',
      answer: 'An infinite 2-regular tree (line)',
      why: 'Same as the Cayley graph of ℤ'
    },
  ];

  const scenario = randomChoice(scenarios);
  const options = shuffle([scenario.answer, 'A finite cycle', 'A complete graph', 'A grid']);

  return {
    type: 'cayley',
    responseType: 'multiple_choice',
    question: scenario.question,
    options,
    correctIndex: options.indexOf(scenario.answer),
    explanation: scenario.why
  };
}

function generateQuestion(difficulty: Difficulty): Question {
  const generators = [
    generateDefinitionQuestion,
    generateReductionQuestion,
    generatePropertyQuestion,
    generateUniversalQuestion,
    generateRankQuestion,
    generateCayleyQuestion,
  ];

  return randomChoice(generators)(difficulty);
}

function generateQuiz(difficulty: Difficulty): Question[] {
  const questions: Question[] = [];
  const usedTypes = new Set<string>();

  while (questions.length < 5) {
    const question = generateQuestion(difficulty);
    if (!usedTypes.has(question.type)) {
      usedTypes.add(question.type);
      questions.push(question);
    }
  }

  return questions;
}

export function FreeGroupsQuiz() {
  const [difficulty, setDifficulty] = useState<Difficulty | null>(null);
  const [questions, setQuestions] = useState<Question[]>([]);
  const [currentQuestion, setCurrentQuestion] = useState(0);
  const [selectedAnswer, setSelectedAnswer] = useState<number | null>(null);
  const [textAnswer, setTextAnswer] = useState('');
  const [showResult, setShowResult] = useState(false);
  const [score, setScore] = useState(0);
  const [quizComplete, setQuizComplete] = useState(false);

  const startQuiz = (diff: Difficulty) => {
    setDifficulty(diff);
    setQuestions(generateQuiz(diff));
    setCurrentQuestion(0);
    setSelectedAnswer(null);
    setTextAnswer('');
    setShowResult(false);
    setScore(0);
    setQuizComplete(false);
  };

  const checkAnswer = () => {
    const question = questions[currentQuestion];
    let isCorrect = false;

    if (question.responseType === 'multiple_choice') {
      isCorrect = selectedAnswer === question.correctIndex;
    } else {
      const normalizedAnswer = textAnswer.trim().toLowerCase();
      isCorrect = question.acceptedAnswers.some(
        ans => ans.toLowerCase() === normalizedAnswer
      );
    }

    if (isCorrect) setScore(score + 1);
    setShowResult(true);
  };

  const nextQuestion = () => {
    if (currentQuestion + 1 >= questions.length) {
      setQuizComplete(true);
    } else {
      setCurrentQuestion(currentQuestion + 1);
      setSelectedAnswer(null);
      setTextAnswer('');
      setShowResult(false);
    }
  };

  if (!difficulty) {
    return (
      <div className="my-8 p-6 bg-gray-900 rounded-xl border border-purple-500/30">
        <h3 className="text-xl font-bold text-purple-300 mb-4">Free Groups Quiz</h3>
        <p className="text-gray-300 mb-4">Test your understanding of free groups, words, and the universal property!</p>
        <div className="flex gap-4 flex-wrap">
          {(['easy', 'medium', 'hard'] as Difficulty[]).map((diff) => (
            <button
              key={diff}
              onClick={() => startQuiz(diff)}
              className={`px-6 py-2 rounded-lg font-medium transition-all ${
                diff === 'easy' ? 'bg-green-600 hover:bg-green-500' :
                diff === 'medium' ? 'bg-yellow-600 hover:bg-yellow-500' :
                'bg-red-600 hover:bg-red-500'
              }`}
            >
              {diff.charAt(0).toUpperCase() + diff.slice(1)}
            </button>
          ))}
        </div>
      </div>
    );
  }

  if (quizComplete) {
    return (
      <div className="my-8 p-6 bg-gray-900 rounded-xl border border-purple-500/30">
        <h3 className="text-xl font-bold text-purple-300 mb-4">Quiz Complete!</h3>
        <p className="text-2xl text-white mb-4">
          Score: {score}/{questions.length} ({Math.round(score/questions.length * 100)}%)
        </p>
        <button
          onClick={() => setDifficulty(null)}
          className="px-6 py-2 bg-purple-600 hover:bg-purple-500 rounded-lg font-medium transition-all"
        >
          Try Again
        </button>
      </div>
    );
  }

  const question = questions[currentQuestion];

  return (
    <div className="my-8 p-6 bg-gray-900 rounded-xl border border-purple-500/30">
      <div className="flex justify-between items-center mb-4">
        <h3 className="text-lg font-bold text-purple-300">
          Question {currentQuestion + 1}/{questions.length}
        </h3>
        <span className="text-gray-400 capitalize">{difficulty}</span>
      </div>

      <p className="text-white text-lg mb-6">{question.question}</p>

      {question.responseType === 'multiple_choice' ? (
        <div className="space-y-3">
          {question.options.map((option, index) => (
            <button
              key={index}
              onClick={() => !showResult && setSelectedAnswer(index)}
              disabled={showResult}
              className={`w-full text-left p-4 rounded-lg border transition-all ${
                showResult
                  ? index === question.correctIndex
                    ? 'bg-green-600/30 border-green-500'
                    : index === selectedAnswer
                    ? 'bg-red-600/30 border-red-500'
                    : 'bg-gray-800 border-gray-600'
                  : selectedAnswer === index
                  ? 'bg-purple-600/30 border-purple-500'
                  : 'bg-gray-800 border-gray-600 hover:border-purple-500'
              }`}
            >
              {option}
            </button>
          ))}
        </div>
      ) : (
        <input
          type="text"
          value={textAnswer}
          onChange={(e) => setTextAnswer(e.target.value)}
          disabled={showResult}
          placeholder="Enter your answer..."
          className="w-full p-4 bg-gray-800 border border-gray-600 rounded-lg text-white focus:border-purple-500 focus:outline-none"
        />
      )}

      {showResult && (
        <div className={`mt-4 p-4 rounded-lg ${
          (question.responseType === 'multiple_choice' && selectedAnswer === question.correctIndex) ||
          (question.responseType === 'free_response' && question.acceptedAnswers.some(a => a.toLowerCase() === textAnswer.trim().toLowerCase()))
            ? 'bg-green-600/20 border border-green-500'
            : 'bg-red-600/20 border border-red-500'
        }`}>
          <p className="text-gray-200">{question.explanation}</p>
        </div>
      )}

      <div className="mt-6 flex justify-end">
        {!showResult ? (
          <button
            onClick={checkAnswer}
            disabled={question.responseType === 'multiple_choice' ? selectedAnswer === null : !textAnswer.trim()}
            className="px-6 py-2 bg-purple-600 hover:bg-purple-500 disabled:bg-gray-600 disabled:cursor-not-allowed rounded-lg font-medium transition-all"
          >
            Check Answer
          </button>
        ) : (
          <button
            onClick={nextQuestion}
            className="px-6 py-2 bg-purple-600 hover:bg-purple-500 rounded-lg font-medium transition-all"
          >
            {currentQuestion + 1 >= questions.length ? 'See Results' : 'Next Question'}
          </button>
        )}
      </div>
    </div>
  );
}
