import { useState } from 'react';

type Difficulty = 'easy' | 'medium' | 'hard';

interface MultipleChoiceQuestion {
  type: string;
  responseType: 'multiple_choice';
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
}

interface FreeResponseQuestion {
  type: string;
  responseType: 'free_response';
  question: string;
  correctAnswer: string;
  acceptedAnswers: string[];
  explanation: string;
}

type Question = MultipleChoiceQuestion | FreeResponseQuestion;

function shuffle<T>(array: T[]): T[] {
  const arr = [...array];
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

function randomChoice<T>(array: T[]): T {
  return array[Math.floor(Math.random() * array.length)];
}

// Ideal definition
function generateIdealDefinitionQuestion(_difficulty: Difficulty): MultipleChoiceQuestion {
  const options = shuffle([
    'A subring I where rI ⊆ I and Ir ⊆ I for all r in the ring',
    'Any subring',
    'A normal subgroup of the additive group',
    'A subset closed under addition'
  ]);

  return {
    type: 'ideal_definition',
    responseType: 'multiple_choice',
    question: 'What is an ideal of a ring R?',
    options,
    correctIndex: options.indexOf('A subring I where rI ⊆ I and Ir ⊆ I for all r in the ring'),
    explanation: 'An ideal I ⊆ R is an additive subgroup that "absorbs" multiplication: for all r ∈ R and a ∈ I, both ra ∈ I and ar ∈ I.'
  };
}

// Is it an ideal?
function generateIsIdealQuestion(difficulty: Difficulty): MultipleChoiceQuestion {
  const scenarios = difficulty === 'easy' ? [
    { subset: 'nℤ in ℤ', isIdeal: true, why: 'n times any integer is still a multiple of n' },
    { subset: '{0} in any ring R', isIdeal: true, why: 'r·0 = 0 for all r' },
    { subset: 'R itself', isIdeal: true, why: 'R is always an ideal of R' },
  ] : difficulty === 'medium' ? [
    { subset: '2ℤ in ℤ', isIdeal: true, why: '(even)·(integer) = even' },
    { subset: 'ℤ in ℚ', isIdeal: false, why: '½ · 2 = 1, but ½ ∈ ℚ and 2 ∈ ℤ while 1 ∉ 2ℤ (wait, ℤ itself... ½·2 = 1 ∈ ℤ. But is ℤ an ideal of ℚ? No, because ℚ·ℤ ⊄ ℤ: ½·2 = 1 ∈ ℤ, but ⅓·3 = 1 ∈ ℤ... actually ℤ absorbs rational mult)' },
    { subset: '⟨x⟩ in ℤ[x]', isIdeal: true, why: 'principal ideal generated by x: polynomials with no constant term' },
  ] : [
    { subset: 'nilpotent elements of a commutative ring', isIdeal: true, why: 'nilradical is an ideal' },
    { subset: 'units of a ring', isIdeal: false, why: 'units form a group under multiplication, not an ideal' },
  ];

  const scenario = randomChoice(scenarios);
  return {
    type: 'is_ideal',
    responseType: 'multiple_choice',
    question: `Is ${scenario.subset} an ideal?`,
    options: ['Yes', 'No'],
    correctIndex: scenario.isIdeal ? 0 : 1,
    explanation: scenario.isIdeal ? `Yes: ${scenario.why}.` : `No: ${scenario.why}.`
  };
}

// Prime ideals
function generatePrimeIdealQuestion(difficulty: Difficulty): MultipleChoiceQuestion {
  const scenarios = difficulty === 'easy' ? [
    { statement: 'If P is prime and ab ∈ P, then a ∈ P or b ∈ P', correct: true, why: 'definition of prime ideal' },
    { statement: '⟨p⟩ is prime in ℤ for p prime', correct: true, why: 'if p | ab then p | a or p | b' },
  ] : difficulty === 'medium' ? [
    { statement: 'R/P is an integral domain iff P is prime', correct: true, why: 'prime ideals correspond to domains' },
    { statement: '⟨6⟩ is prime in ℤ', correct: false, why: '2·3 ∈ ⟨6⟩ but 2 ∉ ⟨6⟩ and 3 ∉ ⟨6⟩' },
  ] : [
    { statement: 'Every maximal ideal is prime', correct: true, why: 'R/M is a field, hence a domain' },
    { statement: 'Every prime ideal is maximal', correct: false, why: '⟨0⟩ in ℤ is prime but not maximal' },
  ];

  const scenario = randomChoice(scenarios);
  return {
    type: 'prime_ideal',
    responseType: 'multiple_choice',
    question: `True or False: ${scenario.statement}`,
    options: ['True', 'False'],
    correctIndex: scenario.correct ? 0 : 1,
    explanation: scenario.why
  };
}

// Maximal ideals
function generateMaximalIdealQuestion(difficulty: Difficulty): MultipleChoiceQuestion {
  const scenarios = difficulty === 'easy' ? [
    { statement: '⟨p⟩ is maximal in ℤ for p prime', correct: true, why: 'ℤ/⟨p⟩ ≅ ℤₚ is a field' },
  ] : difficulty === 'medium' ? [
    { statement: 'R/M is a field iff M is maximal', correct: true, why: 'definition/characterization of maximal ideals' },
    { statement: '⟨2, x⟩ is maximal in ℤ[x]', correct: true, why: 'ℤ[x]/⟨2, x⟩ ≅ ℤ₂ is a field' },
  ] : [
    { statement: 'In a PID, nonzero prime ideals are maximal', correct: true, why: 'prime = irreducible in PIDs, and irreducibles generate maximal ideals' },
    { statement: '⟨x⟩ is maximal in ℤ[x]', correct: false, why: 'ℤ[x]/⟨x⟩ ≅ ℤ, which is not a field' },
  ];

  const scenario = randomChoice(scenarios);
  return {
    type: 'maximal_ideal',
    responseType: 'multiple_choice',
    question: `True or False: ${scenario.statement}`,
    options: ['True', 'False'],
    correctIndex: scenario.correct ? 0 : 1,
    explanation: scenario.why
  };
}

// Quotient rings
function generateQuotientQuestion(difficulty: Difficulty): MultipleChoiceQuestion {
  const scenarios = difficulty === 'easy' ? [
    { ring: 'ℤ', ideal: '⟨n⟩', quotient: 'ℤₙ', why: 'integers mod n' },
  ] : difficulty === 'medium' ? [
    { ring: 'ℤ[x]', ideal: '⟨x⟩', quotient: 'ℤ', why: 'set x = 0, get integers' },
    { ring: 'ℝ[x]', ideal: '⟨x² + 1⟩', quotient: 'ℂ', why: 'adjoin a root of x² + 1' },
  ] : [
    { ring: 'ℤ[x]', ideal: '⟨2, x⟩', quotient: 'ℤ₂', why: '2 = 0 and x = 0, leaving ℤ₂' },
  ];

  const scenario = randomChoice(scenarios);
  const options = shuffle([scenario.quotient, 'ℤ', 'ℚ', 'ℝ']);

  return {
    type: 'quotient',
    responseType: 'multiple_choice',
    question: `What is ${scenario.ring}/${scenario.ideal}?`,
    options,
    correctIndex: options.indexOf(scenario.quotient),
    explanation: scenario.why
  };
}

// Ring homomorphisms
function generateHomomorphismQuestion(difficulty: Difficulty): MultipleChoiceQuestion {
  const scenarios = difficulty === 'easy' ? [
    { statement: 'A ring homomorphism preserves both + and ·', correct: true, why: 'φ(a+b) = φ(a)+φ(b) and φ(ab) = φ(a)φ(b)' },
  ] : difficulty === 'medium' ? [
    { statement: 'The kernel of a ring homomorphism is an ideal', correct: true, why: 'ker φ = {a : φ(a) = 0} is an ideal' },
    { statement: 'Ring homomorphisms must send 1 to 1', correct: false, why: 'not required in general, but often assumed' },
  ] : [
    { statement: 'R/ker(φ) ≅ im(φ) for ring homomorphisms', correct: true, why: 'First Isomorphism Theorem for rings' },
  ];

  const scenario = randomChoice(scenarios);
  return {
    type: 'homomorphism',
    responseType: 'multiple_choice',
    question: `True or False: ${scenario.statement}`,
    options: ['True', 'False'],
    correctIndex: scenario.correct ? 0 : 1,
    explanation: scenario.why
  };
}

function generateQuestion(difficulty: Difficulty): Question {
  const generators = [
    generateIdealDefinitionQuestion,
    generateIsIdealQuestion,
    generatePrimeIdealQuestion,
    generateMaximalIdealQuestion,
    generateQuotientQuestion,
    generateHomomorphismQuestion,
  ];

  return randomChoice(generators)(difficulty);
}

function generateQuiz(difficulty: Difficulty): Question[] {
  const questions: Question[] = [];
  const usedTypes = new Set<string>();

  while (questions.length < 5) {
    const question = generateQuestion(difficulty);
    if (!usedTypes.has(question.type)) {
      usedTypes.add(question.type);
      questions.push(question);
    }
  }

  return questions;
}

export function IdealsQuiz() {
  const [difficulty, setDifficulty] = useState<Difficulty | null>(null);
  const [questions, setQuestions] = useState<Question[]>([]);
  const [currentQuestion, setCurrentQuestion] = useState(0);
  const [selectedAnswer, setSelectedAnswer] = useState<number | null>(null);
  const [textAnswer, setTextAnswer] = useState('');
  const [showResult, setShowResult] = useState(false);
  const [score, setScore] = useState(0);
  const [quizComplete, setQuizComplete] = useState(false);

  const startQuiz = (diff: Difficulty) => {
    setDifficulty(diff);
    setQuestions(generateQuiz(diff));
    setCurrentQuestion(0);
    setSelectedAnswer(null);
    setTextAnswer('');
    setShowResult(false);
    setScore(0);
    setQuizComplete(false);
  };

  const checkAnswer = () => {
    const question = questions[currentQuestion];
    let isCorrect = false;

    if (question.responseType === 'multiple_choice') {
      isCorrect = selectedAnswer === question.correctIndex;
    } else {
      const normalizedAnswer = textAnswer.trim().toLowerCase();
      isCorrect = question.acceptedAnswers.some(
        ans => ans.toLowerCase() === normalizedAnswer
      );
    }

    if (isCorrect) setScore(score + 1);
    setShowResult(true);
  };

  const nextQuestion = () => {
    if (currentQuestion + 1 >= questions.length) {
      setQuizComplete(true);
    } else {
      setCurrentQuestion(currentQuestion + 1);
      setSelectedAnswer(null);
      setTextAnswer('');
      setShowResult(false);
    }
  };

  if (!difficulty) {
    return (
      <div className="my-8 p-6 bg-gray-900 rounded-xl border border-purple-500/30">
        <h3 className="text-xl font-bold text-purple-300 mb-4">Ideals & Quotients Quiz</h3>
        <p className="text-gray-300 mb-4">Test your understanding of ideals, prime ideals, and quotient rings!</p>
        <div className="flex gap-4 flex-wrap">
          {(['easy', 'medium', 'hard'] as Difficulty[]).map((diff) => (
            <button
              key={diff}
              onClick={() => startQuiz(diff)}
              className={`px-6 py-2 rounded-lg font-medium transition-all ${
                diff === 'easy' ? 'bg-green-600 hover:bg-green-500' :
                diff === 'medium' ? 'bg-yellow-600 hover:bg-yellow-500' :
                'bg-red-600 hover:bg-red-500'
              }`}
            >
              {diff.charAt(0).toUpperCase() + diff.slice(1)}
            </button>
          ))}
        </div>
      </div>
    );
  }

  if (quizComplete) {
    return (
      <div className="my-8 p-6 bg-gray-900 rounded-xl border border-purple-500/30">
        <h3 className="text-xl font-bold text-purple-300 mb-4">Quiz Complete!</h3>
        <p className="text-2xl text-white mb-4">
          Score: {score}/{questions.length} ({Math.round(score/questions.length * 100)}%)
        </p>
        <button
          onClick={() => setDifficulty(null)}
          className="px-6 py-2 bg-purple-600 hover:bg-purple-500 rounded-lg font-medium transition-all"
        >
          Try Again
        </button>
      </div>
    );
  }

  const question = questions[currentQuestion];

  return (
    <div className="my-8 p-6 bg-gray-900 rounded-xl border border-purple-500/30">
      <div className="flex justify-between items-center mb-4">
        <h3 className="text-lg font-bold text-purple-300">
          Question {currentQuestion + 1}/{questions.length}
        </h3>
        <span className="text-gray-400 capitalize">{difficulty}</span>
      </div>

      <p className="text-white text-lg mb-6">{question.question}</p>

      {question.responseType === 'multiple_choice' ? (
        <div className="space-y-3">
          {question.options.map((option, index) => (
            <button
              key={index}
              onClick={() => !showResult && setSelectedAnswer(index)}
              disabled={showResult}
              className={`w-full text-left p-4 rounded-lg border transition-all ${
                showResult
                  ? index === question.correctIndex
                    ? 'bg-green-600/30 border-green-500'
                    : index === selectedAnswer
                    ? 'bg-red-600/30 border-red-500'
                    : 'bg-gray-800 border-gray-600'
                  : selectedAnswer === index
                  ? 'bg-purple-600/30 border-purple-500'
                  : 'bg-gray-800 border-gray-600 hover:border-purple-500'
              }`}
            >
              {option}
            </button>
          ))}
        </div>
      ) : (
        <input
          type="text"
          value={textAnswer}
          onChange={(e) => setTextAnswer(e.target.value)}
          disabled={showResult}
          placeholder="Enter your answer..."
          className="w-full p-4 bg-gray-800 border border-gray-600 rounded-lg text-white focus:border-purple-500 focus:outline-none"
        />
      )}

      {showResult && (
        <div className={`mt-4 p-4 rounded-lg ${
          (question.responseType === 'multiple_choice' && selectedAnswer === question.correctIndex) ||
          (question.responseType === 'free_response' && question.acceptedAnswers.some(a => a.toLowerCase() === textAnswer.trim().toLowerCase()))
            ? 'bg-green-600/20 border border-green-500'
            : 'bg-red-600/20 border border-red-500'
        }`}>
          <p className="text-gray-200">{question.explanation}</p>
        </div>
      )}

      <div className="mt-6 flex justify-end">
        {!showResult ? (
          <button
            onClick={checkAnswer}
            disabled={question.responseType === 'multiple_choice' ? selectedAnswer === null : !textAnswer.trim()}
            className="px-6 py-2 bg-purple-600 hover:bg-purple-500 disabled:bg-gray-600 disabled:cursor-not-allowed rounded-lg font-medium transition-all"
          >
            Check Answer
          </button>
        ) : (
          <button
            onClick={nextQuestion}
            className="px-6 py-2 bg-purple-600 hover:bg-purple-500 rounded-lg font-medium transition-all"
          >
            {currentQuestion + 1 >= questions.length ? 'See Results' : 'Next Question'}
          </button>
        )}
      </div>
    </div>
  );
}
