export interface Section {
  id: number;
  title: string;
  slug: string;
  description: string;
}

export interface Part {
  id: number;
  title: string;
  slug: string;
  sections: Section[];
}

export const curriculum: Part[] = [
  {
    id: 1,
    title: "Groups and Subgroups",
    slug: "groups-and-subgroups",
    sections: [
      { id: 0, title: "Sets and Relations", slug: "sets-relations", description: "Foundational set theory and equivalence relations" },
      { id: 1, title: "Binary Operations", slug: "binary-operations", description: "Operations on sets and their properties" },
      { id: 2, title: "Groups", slug: "groups", description: "The group axioms and basic properties" },
      { id: 3, title: "Abelian Examples", slug: "abelian-examples", description: "Commutative groups: integers, rationals, and modular arithmetic" },
      { id: 4, title: "Nonabelian Examples", slug: "nonabelian-examples", description: "Symmetric groups, dihedral groups, and matrix groups" },
      { id: 5, title: "Subgroups", slug: "subgroups", description: "Subsets that form groups" },
      { id: 6, title: "Cyclic Groups", slug: "cyclic-groups", description: "Groups generated by a single element" },
      { id: 7, title: "Generating Sets and Cayley Digraphs", slug: "generating-sets", description: "Visualizing group structure" },
    ]
  },
  {
    id: 2,
    title: "Structure of Groups",
    slug: "structure-of-groups",
    sections: [
      { id: 8, title: "Groups of Permutations", slug: "permutations", description: "Cycle notation and permutation composition" },
      { id: 9, title: "Finitely Generated Abelian Groups", slug: "finitely-generated-abelian", description: "The fundamental theorem of finite abelian groups" },
      { id: 10, title: "Cosets and the Theorem of Lagrange", slug: "cosets-lagrange", description: "Partitioning groups and counting subgroups" },
      { id: 11, title: "Plane Isometries", slug: "plane-isometries", description: "Geometric transformations as group elements" },
    ]
  },
  {
    id: 3,
    title: "Homomorphisms and Factor Groups",
    slug: "homomorphisms-factor-groups",
    sections: [
      { id: 12, title: "Factor Groups", slug: "factor-groups", description: "Quotient groups and normal subgroups" },
      { id: 13, title: "Factor-Group Computations and Simple Groups", slug: "factor-group-computations", description: "Working with quotient structures" },
      { id: 14, title: "Group Action on a Set", slug: "group-actions", description: "Groups acting on sets and orbits" },
      { id: 15, title: "Applications of G-Sets to Counting", slug: "gsets-counting", description: "Burnside's lemma and Polya counting" },
    ]
  },
  {
    id: 4,
    title: "Advanced Group Theory",
    slug: "advanced-group-theory",
    sections: [
      { id: 16, title: "Isomorphism Theorems", slug: "isomorphism-theorems", description: "The three fundamental isomorphism theorems" },
      { id: 17, title: "Sylow Theorems", slug: "sylow-theorems", description: "p-subgroups and their properties" },
      { id: 18, title: "Series of Groups", slug: "series-of-groups", description: "Composition series and solvable groups" },
      { id: 19, title: "Free Abelian Groups", slug: "free-abelian-groups", description: "Abelian groups with a basis" },
      { id: 20, title: "Free Groups", slug: "free-groups", description: "Groups with no relations" },
      { id: 21, title: "Group Presentations", slug: "group-presentations", description: "Describing groups by generators and relations" },
    ]
  },
  {
    id: 5,
    title: "Rings and Fields",
    slug: "rings-and-fields",
    sections: [
      { id: 22, title: "Rings and Fields", slug: "rings-fields-intro", description: "Two-operation algebraic structures" },
      { id: 23, title: "Integral Domains", slug: "integral-domains", description: "Rings without zero divisors" },
      { id: 24, title: "Fermat's and Euler's Theorems", slug: "fermat-euler", description: "Modular exponentiation theorems" },
      { id: 25, title: "Encryption", slug: "encryption", description: "RSA and public-key cryptography" },
    ]
  },
  {
    id: 6,
    title: "Constructing Rings and Fields",
    slug: "constructing-rings-fields",
    sections: [
      { id: 26, title: "The Field of Quotients of an Integral Domain", slug: "field-of-quotients", description: "Building fractions from integers" },
      { id: 27, title: "Rings of Polynomials", slug: "polynomial-rings", description: "Polynomial arithmetic and structure" },
      { id: 28, title: "Factorization of Polynomials over a Field", slug: "polynomial-factorization", description: "Irreducibility and unique factorization" },
      { id: 29, title: "Algebraic Coding Theory", slug: "coding-theory", description: "Error detection and correction" },
      { id: 30, title: "Homomorphisms and Factor Rings", slug: "ring-homomorphisms", description: "Structure-preserving maps between rings" },
      { id: 31, title: "Prime and Maximal Ideals", slug: "prime-maximal-ideals", description: "Special ideals and their factor rings" },
      { id: 32, title: "Noncommutative Examples", slug: "noncommutative-rings", description: "Matrix rings and quaternions" },
    ]
  },
  {
    id: 7,
    title: "Commutative Algebra",
    slug: "commutative-algebra",
    sections: [
      { id: 33, title: "Vector Spaces", slug: "vector-spaces", description: "Modules over a field" },
      { id: 34, title: "Unique Factorization Domains", slug: "ufds", description: "Rings with unique factorization" },
      { id: 35, title: "Euclidean Domains", slug: "euclidean-domains", description: "Domains with division algorithm" },
      { id: 36, title: "Number Theory", slug: "number-theory", description: "Algebraic number theory applications" },
      { id: 37, title: "Algebraic Geometry", slug: "algebraic-geometry", description: "Varieties and ideals" },
      { id: 38, title: "Gröbner Bases for Ideals", slug: "grobner-bases", description: "Computational commutative algebra" },
    ]
  },
  {
    id: 8,
    title: "Extension Fields",
    slug: "extension-fields",
    sections: [
      { id: 39, title: "Introduction to Extension Fields", slug: "extension-fields-intro", description: "Building larger fields" },
      { id: 40, title: "Algebraic Extensions", slug: "algebraic-extensions", description: "Roots of polynomials" },
      { id: 41, title: "Geometric Constructions", slug: "geometric-constructions", description: "Compass and straightedge constructions" },
      { id: 42, title: "Finite Fields", slug: "finite-fields", description: "Fields with finitely many elements" },
    ]
  },
  {
    id: 9,
    title: "Galois Theory",
    slug: "galois-theory",
    sections: [
      { id: 43, title: "Introduction to Galois Theory", slug: "galois-intro", description: "Field automorphisms and fixed fields" },
      { id: 44, title: "Splitting Fields", slug: "splitting-fields", description: "Fields where polynomials factor completely" },
      { id: 45, title: "Separable Extensions", slug: "separable-extensions", description: "Extensions with distinct roots" },
      { id: 46, title: "Galois Theory", slug: "galois-theory-main", description: "The fundamental theorem of Galois theory" },
      { id: 47, title: "Illustrations of Galois Theory", slug: "galois-illustrations", description: "Examples and applications" },
      { id: 48, title: "Cyclotomic Extensions", slug: "cyclotomic-extensions", description: "Roots of unity" },
      { id: 49, title: "Insolvability of the Quintic", slug: "insolvability-quintic", description: "Why fifth-degree equations can't be solved by radicals" },
    ]
  },
];

export const getAllSections = (): Section[] => {
  return curriculum.flatMap(part => part.sections);
};

export const getSectionById = (id: number): Section | undefined => {
  return getAllSections().find(s => s.id === id);
};

export const getPartBySectionId = (sectionId: number): Part | undefined => {
  return curriculum.find(part =>
    part.sections.some(section => section.id === sectionId)
  );
};

export const getAdjacentSections = (sectionId: number): { prev?: Section; next?: Section } => {
  const allSections = getAllSections();
  const index = allSections.findIndex(s => s.id === sectionId);

  return {
    prev: index > 0 ? allSections[index - 1] : undefined,
    next: index < allSections.length - 1 ? allSections[index + 1] : undefined,
  };
};

export const getTotalSections = (): number => {
  return getAllSections().length;
};
